### ISSUE TITLE
Popup: not resizable 

### ISSUE THREAD

**Issue by oterral** [geoadmin/mf-geoadmin3#1401]
I think we could something at least with the css3 property `resize`.

https://developer.mozilla.org/de/docs/Web/CSS/resize

**Comment by ponceta** [comment]
Note: Internet Explorer and Opera do not support the resize property.

**Comment by oterral** [comment]
only IE : http://caniuse.com/#search=resize

**Comment by ponceta** [comment]
[Testlink](http://mf-geoadmin3.dev.bgdi.ch/ltpoa/)

For me there is no great plus-value since our interface is responsive and adapts to the user resolution and device and bring to the user the best experience possible (which includes already the best popups sizes possible) It should not be the user job to have to resize the popups (if he does, that means that we failed bringing him the resolutions he expected)

**Comment by cedricmoullet** [comment]
Please try with several lubis features. 

![image](https://cloud.githubusercontent.com/assets/319676/7247745/13c7a45e-e80d-11e4-8640-88925c2924af.png)

the content is not resized

**Comment by ponceta** [comment]
This comes from our defined max height and max width popups content containers.

If we want to go further with this, we should probably list first the popups we WANT to be resizable and the ones we do not want to, right?

**Comment by gjn** [comment]
Despite my +1 at the start, I tend to support Arnaud's view: we should make the content to fit the pre-defined size. Resizing complexifies the UI...not sure we really want this with our usability efforts we want to make.

**Comment by oterral** [comment]
I close this since the resizable thing introduce too much css complexity and the dynamic size of poup has been improved with  https://github.com/geoadmin/mf-geoadmin3/pull/728
