### ISSUE TITLE
Add topic in layer search section

### ISSUE THREAD

**Issue by loicgasser** [geoadmin/mf-geoadmin3#1666]
Need sphinx index adaptation first.
Maybe some adaptation on chsdi side as well.

![topic_search](https://cloud.githubusercontent.com/assets/3306154/4316568/6c280b10-3f08-11e4-895a-d5be52372081.png)

**Comment by cedricmoullet** [comment]
@davidoesch ?

**Comment by davidoesch** [comment]
I see the use case for the topics avaiation and wildruhezonen....in an optimal world you wont need the layertree /catalog: you get everything in the search

-> yes

**Comment by mariokeusen** [comment]
What is the status of this? Is it a definite decision that topic-search will be implemented? (The people from wildruhezonen just asked me)

Thanks for a short info.

**Comment by davidoesch** [comment]
we are working on a major refactoring, based on the usability study. and we will improve the search
@cedricmoullet one point we have to take into account

**Comment by ltclm** [comment]
agree with afoletti. dont see any added value in a topic search. but we could tag the included layers with the topic title.

**Comment by davidoesch** [comment]
As soon as they bring in all the keywords they need in the abstract: layer will be found.

**Comment by davidoesch** [comment]
Since we have a lot of single topic maps (https://docs.google.com/spreadsheets/d/11zjWdLgaCZWiFhB8kP2AWhOb9vKBqLuXeXDPTSd4rDk/edit?pli=1#gid=0) and Topics it makes sense to add them under the map results, with a prefix "Topic" or "Theme". for a fist step we just add the the topic name to the search index, in a second step we can even add an abstract field where we KOGIS control the content and we can improve the SEO for a topic as we think it is best....independent form the metadata of the layers

**Comment by loicgasser** [comment]
Still a wanted feature? Should be found as the same section as the layers with a different look to know we are dealing with topic?
When selecting a topic we could trigger a topic change. @davidoesch Topics should come before or after maps in the ranking? Also, shouldn't we add related keywords for the topics, it would make more sense to do it once and for all. Do you see somebody that could take care of that at IKP?

**Comment by davidoesch** [comment]
still a wanted feature
"Topics should come before or after maps in the ranking?"

-> yes

"add related keywords for the topics, it would make more sense to do it once and for all"

-> here I propose to deal with keywords for topic directly in the BOD (since there is now topic enty in geocat...)

 Do you see somebody that could take care of that at IKP?

-> assign that to me/ @mariokeusen

**Comment by loicgasser** [comment]
So Topic first

and I open an issue for topic keywords.

**Comment by oterral** [comment]
@loicgasser Is chsdi ready for this ?

**Comment by gjn** [comment]
AFAIK, we are waiting for the topic keyword lost. @mariokeusen @davidoesch

**Comment by davidoesch** [comment]
pls  define "topic keyword lost"?

**Comment by gjn** [comment]
lost=list

**Comment by davidoesch** [comment]
Since we use the topic catalog in a first step and not the single topics map we have above listed in the spreadsheet: I'll will define topic keywords for each Lang in a CSV file. We can then have look in a second step on how we maintain it (bod directly...)

**Comment by davidoesch** [comment]
ping @davidoesch

**Comment by pakb** [comment]
Is this really a requested feature?
Anyone aware of "Topics" should now how to select one by the "Change topic" feature and thus this enhancement would add a new layer of complexity hardly needed to the search feature.

**Comment by davidoesch** [comment]
Roth

**Comment by ltclm** [comment]
in my eyes, this should not be done in geocat, it is a geo.admin.ch configuration item which should be maintained in bod. we're able to tag layers as we want in the bod (bod_master.public.dataset_tag):

> agree with afoletti. dont see any added value in a topic search. but we could tag the included layers with the topic title.

i dont think that the data owner should modifiy the layer abstract that there are all the topic keywords in it. topic selection in map.geo.admin.ch can be independant from layer abstract.

**Comment by boecklic** [comment]
@boecklic commented: @davidoesch ?

**Comment by boecklic** [comment]
@boecklic commented: I see the use case for the topics avaiation and wildruhezonen....in an optimal world you wont need the layertree /catalog: you get everything in the search

-> yes

**Comment by boecklic** [comment]
@boecklic commented: What is the status of this? Is it a definite decision that topic-search will be implemented? (The people from wildruhezonen just asked me)

Thanks for a short info.

**Comment by boecklic** [comment]
@boecklic commented: we are working on a major refactoring, based on the usability study. and we will improve the search
@cedricmoullet one point we have to take into account

**Comment by boecklic** [comment]
@boecklic commented: agree with afoletti. dont see any added value in a topic search. but we could tag the included layers with the topic title.

**Comment by boecklic** [comment]
@boecklic commented: As soon as they bring in all the keywords they need in the abstract: layer will be found.

**Comment by boecklic** [comment]
@boecklic commented: Since we have a lot of single topic maps (https://docs.google.com/spreadsheets/d/11zjWdLgaCZWiFhB8kP2AWhOb9vKBqLuXeXDPTSd4rDk/edit?pli=1#gid=0) and Topics it makes sense to add them under the map results, with a prefix "Topic" or "Theme". for a fist step we just add the the topic name to the search index, in a second step we can even add an abstract field where we KOGIS control the content and we can improve the SEO for a topic as we think it is best....independent form the metadata of the layers

**Comment by boecklic** [comment]
@boecklic commented: Still a wanted feature? Should be found as the same section as the layers with a different look to know we are dealing with topic?
When selecting a topic we could trigger a topic change. @davidoesch Topics should come before or after maps in the ranking? Also, shouldn't we add related keywords for the topics, it would make more sense to do it once and for all. Do you see somebody that could take care of that at IKP?

**Comment by boecklic** [comment]
@boecklic commented: still a wanted feature
"Topics should come before or after maps in the ranking?"

-> yes

"add related keywords for the topics, it would make more sense to do it once and for all"

-> here I propose to deal with keywords for topic directly in the BOD (since there is now topic enty in geocat...)

 Do you see somebody that could take care of that at IKP?

-> assign that to me/ @mariokeusen

**Comment by boecklic** [comment]
@boecklic commented: So Topic first

and I open an issue for topic keywords.

**Comment by boecklic** [comment]
@boecklic commented: @loicgasser Is chsdi ready for that ?

**Comment by boecklic** [comment]
@boecklic commented: AFAIK, we are waiting for the topic keyword list. @mariokeusen @davidoesch 

Edit: typo

**Comment by boecklic** [comment]
@boecklic commented: lost=list

**Comment by boecklic** [comment]
@boecklic commented: Since we use the topic catalog in a first step and not the single topics map we have above listed in the spreadsheet: I'll will define topic keywords for each Lang in a CSV file. We can then have look in a second step on how we maintain it (bod directly...)

**Comment by boecklic** [comment]
@boecklic commented: ping @davidoesch

**Comment by boecklic** [comment]
@boecklic commented: Is this really a requested feature?
Anyone aware of "Topics" should now how to select one by the "Change topic" feature and thus this enhancement would add a new layer of complexity hardly needed to the search feature.

**Comment by boecklic** [comment]
@boecklic commented: Nope. This is still on the feature list. PO decides when feature is closed

**Comment by boecklic** [comment]
@boecklic commented: in my eyes, this should not be done in geocat, it is a geo.admin.ch configuration item which should be maintained in bod. we're able to tag layers as we want in the bod (bod_master.public.dataset_tag):

> agree with afoletti. dont see any added value in a topic search. but we could tag the included layers with the topic title.

i dont think that the data owner should modifiy the layer abstract that there are all the topic keywords in it. topic selection in map.geo.admin.ch can be independant from layer abstract.
