### ISSUE TITLE
Allow multiple time-enabled layers to be multi-printed.

### ISSUE THREAD

**Issue by oterral** [geoadmin/mf-geoadmin3#2099]
When we duplicate the layer zeitreiehen we can't print a time series pdf (no checkbox)

http://map.geo.admin.ch/?lang=en&topic=ech&bgLayer=voidLayer&X=151568.85&Y=536389.73&zoom=9&layers=ch.swisstopo.zeitreihen,ch.swisstopo.zeitreihen&layers_timestamp=19641231,19641231&time=1964

**Comment by procrastinatio** [comment]
Well OK, but what is the goal to print twice the very same layer but to challenge the print server ?

So, I make a check if the same 'time enabled' layer is selected and if the same year is selected on both, we may multiprint, OK ?

**Comment by oterral** [comment]
yes or print with the bigger date.

**Comment by procrastinatio** [comment]
I don't know, 'multiprint' is explicitely deactivated if more than one layer _ch.swisstopo.zeitreihen_ is present (see https://github.com/geoadmin/mf-geoadmin3/blob/master/src/components/print/PrintDirective.js#L905), otherwise it is the normal behaviour (top-most layers printed last)

But problems occur when we mix 'ch_swisstopo.zeitreihen' and LUBIS'

**Comment by gjn** [comment]
Yes, excluded explicitely https://github.com/geoadmin/mf-geoadmin3/blob/master/src/components/print/PrintDirective.js#L909, just thought it wouldn't make sense and bach-end might need to be adapted if we want to get rid of this limitation (would need to check)

**Comment by davidoesch** [comment]
'ch_swisstopo.zeitreihen' and LUBIS' printing at the same time: this is a valid use case...

**Comment by cedricmoullet** [comment]
the question is if we make a service for lubis (equivalent to zeitreihen) or if we simply take all years.

**Comment by davidoesch** [comment]
We will have further layers with points /raster besides LUBIS and zeitreihen which will be duplicated and shown on a yr by yr basis. Volkszaehlung for example . So we will need for each layer now a distinct service? 

IMHO yes we a generic service for all those layers

**Comment by gjn** [comment]
@davidoesch Could you describe the use case and how it should behave in the OP? Thanks alot.

**Comment by davidoesch** [comment]
use case

user starts map.lubis,  selects to 1996 adds zeitreihen since he wants to print the map  and the pictures taken  every year http://s.geo.admin.ch/62f178bb7f 

prints:
current result: historical map for each year and always 1996 imagery
expected result: historical map for each year and imagery of corresponding year


then he prints

**Comment by procrastinatio** [comment]
To summarize:
1. not timeEnabled layer: always printing
2. timeEnabled layer: print if year exists, unless a given year is selected.
Right ?

**Comment by davidoesch** [comment]
@procrastinatio :correct

**Comment by davidoesch** [comment]
ping @procrastinatio

**Comment by procrastinatio** [comment]
Pre-required condition: https://github.com/geoadmin/mf-chsdi3/issues/2698

**Comment by davidoesch** [comment]
I close this,  curretn prod solution fits the pareto principle
