### ISSUE TITLE
HTTPS per default

### ISSUE THREAD

**Issue by cedricmoullet** [geoadmin/mf-geoadmin3#2238]
Knowns issues:

 - [x] Help: images in html content
 - [ ] Import WMS : Url of tiles WMS layer added
 - [ ] Import KML: Images google in kml and link to KML validator
 - [ ] Map: Sometimes tiles SSL error with WMTS. and urls of WMS layers like luftfahrthindernisse are http

**Comment by cedricmoullet** [comment]
@davidoesch @hpchrist Do you agree to go on HTTPS per default ?

**Comment by hpchrist** [comment]
yes, on the infra side, the startcom extended validation SSL certificates are ready and seem to well support the wast majority of browsers (in comparison to the BIT certificates;-). But what about the application? Did you already check all directly embedded links to non https resources (in the worst case even outside our FSDI)?

**Comment by davidoesch** [comment]
Help: images in html content
-> We move them away from dav to a https s3 bucket
Import WMS : Url of tiles WMS layer added
-> if we have an ssl warning: IMHO the user can live with that if he gets a ssl error due to a permalink with a WMS over http only
Import KML: Images google in kml and link to KML validator
- Images google: ok this one is tricky since it used often:can the user live with an SSL error here? what happens it will not work? other workarounds? galdos KML validator: we can move it to the help ( o gosh, https as well.....) 
Map: Sometimes tiles SSL error with WMTS. and urls of WMS layers like luftfahrthindernisse are http

-> this one is  a show stopper:"Sometimes tiles SSL error with WMTS" why? WMS layers we have to fix

**Comment by davidoesch** [comment]
Help: images in html content
-> We move them away from dav to a https s3 bucket
Import WMS : Url of tiles WMS layer added
-> if we have an ssl warning: IMHO the user can live with that if he gets a ssl error due to a permalink with a WMS over http only
Import KML: Images google in kml and link to KML validator
- Images google: ok this one is tricky since it used often:can the user live with an SSL error here? what happens it will not work? other workarounds? galdos KML validator: we can move it to the help ( o gosh, https as well.....) 
Map: Sometimes tiles SSL error with WMTS. and urls of WMS layers like luftfahrthindernisse are http

-> this one is  a show stopper:"Sometimes tiles SSL error with WMTS" why? WMS layers we have to fix

**Comment by davidoesch** [comment]
Help: images in html content
-> We move them away from dav to a https s3 bucket
Import WMS : Url of tiles WMS layer added
-> if we have an ssl warning: IMHO the user can live with that if he gets a ssl error due to a permalink with a WMS over http only
Import KML: Images google in kml and link to KML validator
- Images google: ok this one is tricky since it used often:can the user live with an SSL error here? what happens it will not work? other workarounds? galdos KML validator: we can move it to the help ( o gosh, https as well.....) 
Map: Sometimes tiles SSL error with WMTS. and urls of WMS layers like luftfahrthindernisse are http

-> this one is  a show stopper:"Sometimes tiles SSL error with WMTS" why? WMS layers we have to fix

**Comment by hpchrist** [comment]
I think we have to accept "mixed content" warnings, when users include "thirdparty" content (for example kml, wms, etc.). It is, as said, a warning for the user and NOT an error. But we should try to avoid these kind of warnings, when geodamin is used without adding "thirdparty" content.

@cedricmoullet Regarding the current mixed content warning in Chrome when opening https://map.geo.admin.ch: I guess this is due to the help next to the search bar. It contains external images from htt*p*://help.geo.admin.ch, for example: <img ng-src="http://help.geo.admin.ch/img/24d.jpg" draggable="false" src="http://help.geo.admin.ch/img/24d.jpg">

**Comment by ponceta** [comment]
@hpchrist @pauloamado help could also be in https right? Or it requires another certificate?

**Comment by hpchrist** [comment]
@ponceta yes, the certificate *.geo.admin.ch as well covers help.geo.admin.ch

**Comment by ponceta** [comment]
Ok, I've translated the links into html, I'll see tomorrow with @pauloamado if we can change the links in the sidebar (now they are redirecting to http addresses)

**Comment by gjn** [comment]
@oterral Can we do anything about the kmlvalidator in html? ng-if?

**Comment by davidoesch** [comment]
If this helps : we can put the kml validator link into help.geo.admin.ch...

**Comment by oterral** [comment]
In fact the link only submit a `form`, so the url is in the  `action` attribute of the `form` so the `ng-if` can't be used here.

**Comment by oterral** [comment]
Don't know if it's relevant but https://map.bafu.admin.ch/ doesn't work @hpchrist

**Comment by hpchrist** [comment]
@oterral we don't have a certificate in place that covers bafu!

@davidoesch @cedricmoullet: this shows again, that all concessions/exceptions are bad, bad, bad! In my opinion, this issue should be taken as an opportunity to convince the BAFU, that map.bafu.admin.ch should be a redirect to map.geo.admin.ch, basta! @davidoesch: do you agree?

**Comment by davidoesch** [comment]
Will work in that...

**Comment by ponceta** [comment]
[help.geo.admin](https://help.geo.admin.ch)

is now fully "HTTPS ready".

For chrome, having a link to http webpage is not a problem but USING the content of an http ressource is indeed considered as an https infraction. In our case the kml validator is one of these infractions.

**Comment by cedricmoullet** [comment]
As proposed by @hpchrist, we have to fix our content.
So, we still have "Map: Sometimes tiles SSL error with WMTS. and urls of WMS layers like luftfahrthindernisse are http" to do

**Comment by cedricmoullet** [comment]
@hpchrist could you configure an automatic redirection in dev and int ?

**Comment by cedricmoullet** [comment]
@AFoletti could you fix the source of luftfahrthindernis ?

**Comment by hpchrist** [comment]
Redirect of dev and int will be implemented for testing this week.

**Comment by ponceta** [comment]
Nice! :)
