### ISSUE TITLE
Swissearch is broken on IE 10

### ISSUE THREAD

**Issue by alcapat** [geoadmin/mf-geoadmin3#2395]
HTTP 400 with IE 10 when we try to search a word with a special caracter like ä, à,...

Example :
- request return a result : https://mf-geoadmin3.ci.bgdi.ch/?swisssearch=bruckenmoostrasse  
- request return an error : https://mf-geoadmin3.ci.bgdi.ch/?swisssearch=brückenmoostrasse

**Comment by alcapat** [comment]
it work's on prod. the character ü is replaced by "%C3%BC on the url.
The problem is only visible on CI and DEV not on PROD

**Comment by gjn** [comment]
It seems that this error did not happen because of code changes, as we have the same troubles with versions that have worked before. It looks like something in the infrastructure made this happen.

For information, using http works:
https://mf-geoadmin3.ci.bgdi.ch/?swisssearch=brückenmoostrasse

Also, on production, but http and https work:
http://map.geo.admin.ch/?swisssearch=brückenmoostrasse
https://map.geo.admin.ch/?swisssearch=brückenmoostrasse

**Comment by gjn** [comment]
It's working on integration.

**Comment by gjn** [comment]
@oterral @procrastinatio Care to take a look?

**Comment by cedricmoullet** [comment]
Just tested and works fine on https on ci and prod. I close this ticket
