### ISSUE TITLE
wms/balz layer not shown in A3 print

### ISSUE THREAD

**Issue by gjn** [geoadmin/mf-geoadmin3#2718]
From helpdesk:

 Guten Tag
Wir haben ein Problem festgestellt beim erstellen eines PDFs. Wenn man im map.bazl... mit den Hindernissen darauf eine A3 Seite erstellt, dann sind die Hindernisse nicht mehr darauf. Nur bei A4 funktioniert es dass die Hindernisse auch im PDF korrekt dargestellt werden. Das Problem bestand aber vor einigen Monaten nicht, da hatten wir es genau gleich gemacht und es funktionierte.
Vielen Dank
Mit freundlichen Grüssen. 
Permalink: https://map.geo.admin.ch/?topic=aviation&lang=de&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=ch.bazl.luftfahrthindernis&catalogNodes=1379,1381,1514&X=178937.75&Y=663758.75&zoom=4. 

Could verify with chrome.

@procrastinatio Could you have a quick look?

**Comment by procrastinatio** [comment]
Ich nehme an, das Bild ist zu gross und der WMS Dienst liefert nichts beim A3.

**Comment by procrastinatio** [comment]
The print server is making a single tile WMS (1619x2396) request for A3:

`curl -I -L "http://wms.geo.admin.ch/?BBOX=510326.3923339844%2C129722.91666666667%2C713173.6076660156%2C266777.0833333333&HEIGHT=1619&WIDTH=2396&EXCEPTIONS=XML&TRANSPARENT=true&map_resolution=150&CRS=EPSG%3A21781&VERSION=1.1.1&FORMAT=image%2Fpng&SERVICE=WMS&format_options=dpi%3A150&LAYERS=ch.bazl.luftfahrthindernis&REQUEST=GetMap&STYLES=&DPI=150&SRS=EPSG%3A21781"`

Image is too big...

```
<!DOCTYPE ServiceExceptionReport SYSTEM "http://schemas.opengis.net/wms/1.1.1/exception_1_1_1.dtd">
<ServiceExceptionReport version="1.1.1">
<ServiceException>
msWMSLoadGetMapParams(): WMS server error. Image size out of range, WIDTH and HEIGHT must be between 1 and 2048 pixels.
</ServiceException>
</ServiceExceptionReport>
```
Apparently, the layer has to be single tile in map.geo.admin.ch because it must display a timestamp (`ch.bazl.luftfahrthindernis_datenstand`), embended in the data. So switching to tiles wms is not a option ( is it true @ltclm @AFoletti ?)

So the only options is to increase the image size in WMS (2400x2400)

**Comment by gjn** [comment]
Well, IMO, basic problem is that the datenstand is part of the wms image. We should fix that and then switch to wms-c for this data.

Datenstand could be a (new) service of our API.

**Comment by procrastinatio** [comment]
The `datenstand`is also in the [legend](https://api3.geo.admin.ch/rest/services/all/MapServer/ch.bazl.luftfahrthindernis/legend?lang=de)

We could also do an aggregate layer of it:
* point, line and polygon as WMS-C
* datenstand as single tiled WMS

**Comment by procrastinatio** [comment]
@gjn @ltclm @AFoletti Datenstand is already in the legend. Has it to be displayed on the map ? The real trouble is that this information is in the BOD and the layer's table. If the layer fails to deploy but not the BOD, you may have two `datenstand`.

**Comment by procrastinatio** [comment]
Please test against `wms-bgdi.dev.bgdi.ch`

**Comment by procrastinatio** [comment]
See PR https://github.com/geoadmin/wms-bgdi/issues/11

**Comment by procrastinatio** [comment]
@AFoletti @ltclm Could you please deploy the WMS-BGDI service to prod ?

**Comment by cedricmoullet** [comment]
@alcapat @AFoletti @ltclm Have you deployed the WMS BGDI ?

**Comment by mariokeusen** [comment]
Could verify with Chrome and IE.
I can only confirm that, yes, the Datenstand has to be present on the map due to safety reasons, especially for the print use-case. This was a MUST condition by the data owner when we first-integrated this layer.

**Comment by AFoletti** [comment]
we sill have a problem with the wms-bgdi translation. The maxsize setted by the mentioned PR is present only in the DEV version of the file.
I'm checking that and will deploy ASAP

**Comment by AFoletti** [comment]
wms-bgdi is deployed to PROD.
Maxsize is now 3850px, in order to allow A3 print and use of the WMS on UltraHD monitors

test [here] (https://wms.geo.admin.ch/?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image%2Fpng&TRANSPARENT=true&LAYERS=ch.bazl.luftfahrthindernis&CRS=EPSG%3A21781&STYLES=&WIDTH=3200&HEIGHT=3200&BBOX=633150%2C177845%2C652350%2C184915)

**Comment by gjn** [comment]
Working fine. Thanks alot.
