### ISSUE TITLE
activate preselected layer via search

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#2740]
all browsers

start app
 search for adresses "Gebäude- und Wohnungsregister"

-> layer is  loaded - but cant' be activated via all in one search

expected result:

if a layer is searched for and he is already in the availbale layer list: he can be activated via all in one search

**Comment by gjn** [comment]
This affects all pre-selected layers.

The reason is probably that these layers are already added to the map, but invisible. So clicking them does nothing because usually a click adds a map with default visibility.

What should happen? Should we activate the layer on click? For all layers in the layer manager?

**Comment by davidoesch** [comment]
expected result:

if a layer is searched for and he is already in the availbale layer list: he can be activated via all in one search

**Comment by oterral** [comment]
Fixed by PR
