### ISSUE TITLE
Object filtering/ Query tool : more than 2 Conditions

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#2745]
with an Advanced search operator (and/or function) it would be helpful to
- [ ] have more more then 2 search condtions and set for each condition the boolean operator 
- [ ] and NOT as operatore (with this we support all three basic boolean operators)

**Comment by gjn** [comment]
We decided against multiple and/or because it would cluster the UI and there's no user friendly way to put the parantheses...user would basically need to write part od query by hand.

Having not operator does make sense.

Proposal: wait for feedback of new and/or and analyse usage and re-discuss in a couple of weeks.

**Comment by oterral** [comment]
+1 for let the user specify himself the query string for more complex search. There is no nice UI way to do that in the tiny small popup.

**Comment by cedricmoullet** [comment]
Let's go with this version for now.

2015-10-08 7:43 GMT+02:00 oterral <notifications@github.com>:

> +1 for let the user specify himself the query string for more complex
> search. There is no nice UI way to do that in the tiny small popup.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geoadmin/mf-geoadmin3/issues/2745#issuecomment-146425976>
> .
>



-- 
Twitter: http://twitter.com/cedricmoullet
Linked In: http://www.linkedin.com/in/cedricmoullet

<http://twitter.com/cedricmoullet>

**Comment by davidoesch** [comment]
we remove  - this since in RE4...we might not have it at all
