### ISSUE TITLE
3D Broken on FireFox

### ISSUE THREAD

**Issue by gjn** [geoadmin/mf-geoadmin3#2826]
With the merging of the [auto-render loop](https://github.com/geoadmin/mf-geoadmin3/pull/2814), 3D is not working anymore on FF41 and FF42.

Previoues version (e.g. https://github.com/geoadmin/mf-geoadmin3/commit/e839a0da00a429846ed9245c6704a7341984ce85) works fine.

@gberaudo Could you have a look?

**Comment by gberaudo** [comment]
I see several issues, maybe unrelated, on all browsers.
Is your issue specific to firefox? Which particular issue is it?

First I disabled autorender loop by passing the [&autorender=false](https://mf-geoadmin3.dev.bgdi.ch/gberaudo_autorenderloop/src/?dev3d=true&lang=en&topic=ech&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=ch.swisstopo.zeitreihen,ch.bfs.gebaeude_wohnungs_register,ch.bafu.wrz-wildruhezonen_portal,ch.swisstopo.swisstlm3d-wanderwege&layers_visibility=false,false,false,false&layers_timestamp=18641231,,,&autorender=false&X=197600.00&Y=658450.00&zoom=0]) parameter and zoomed out to the maximum in 2D.

Then I click on the 3D button and I see the position of Switzerland is wrong, too close to the top of the screen. This seems due to the limitiation of the camera in the Swiss extent. @fredj is looking at it.

When I disabled the limitation, I get a black screen, but after moving a bit towards Switzerland, it soudaintly appears, correctly positionned. I guess it is due to the minimumRetrievingLevel we set on the imageries which is too low.

**Comment by gberaudo** [comment]
When passing `minimumRetrievingLevel=5`, it fixes the black screen issue.

**Comment by gjn** [comment]
What I was reporting was only on FF.

3D worked before merging https://github.com/geoadmin/mf-geoadmin3/pull/2814
After this merge (current master), it doesn't work anymore. I never get anything shown, but I think data is downloaded. Can you reproduce this in FF? (I'm on win7)

AFAIK, we didn't change the `minimumRetrievingLevel ` in https://github.com/geoadmin/mf-geoadmin3/pull/2814, so I guess what you are observing is a different effect.

**Comment by gberaudo** [comment]
I downloaded firefox 42 (linux) and it is working the same as other browsers.
What did you observed and what steps did you follow?

**Comment by gjn** [comment]
I was obviously being stupid. Can't reproduce anymore on FF.

Anyhow, as noted above, current behaviour when zooming out is not perfect (I think fred is working on that currently).

I'll close this one. Sorry for the inconvenience.
