### ISSUE TITLE
3D White background is not white but contains a BG layer. It should be empty

### ISSUE THREAD

**Issue by cedricmoullet** [geoadmin/mf-geoadmin3#2837]

**Comment by gjn** [comment]
As long as we don't have lighting, we can't have white background, otherwise, nothing can be seen in 3D.

**Comment by cedricmoullet** [comment]
It s for the draping of layer. Simply geology with terrain, for exemple. Isn't it possible ?

Envoyé de mon iPhone

**Comment by gjn** [comment]
Sure, we can drape any layer that we want if void layer is selected. But to see anything, we have to drape something (as long as we don't have lighting).

draping a white layer won't help because in 3D, you won't see anything.

**Comment by cedricmoullet** [comment]
For me it s fine if we need to add a layer. Empty is empty 

Envoyé de mon iPhone

**Comment by gjn** [comment]
hmm. I can prepare a demo, but we will only see white...

**Comment by gjn** [comment]
If starting with voidlayer in permalink, the effect can already be seen:

[See here](https://mf-geoadmin3.dev.bgdi.ch/?dev3d=true&topic=ech&lang=de&bgLayer=voidLayer&layers=ch.swisstopo.zeitreihen,ch.bfs.gebaeude_wohnungs_register,ch.bafu.wrz-wildruhezonen_portal,ch.swisstopo.swisstlm3d-wanderwege&layers_visibility=false,false,false,false&layers_timestamp=18641231,,,&mobile=false&lon=8.02483&lat=46.55637&elevation=25749&heading=7.513&pitch=-39.715)

**Comment by gjn** [comment]
[Testlink](https://mf-geoadmin3.dev.bgdi.ch/?dev3d=true&topic=ech&lang=de&bgLayer=voidLayer&layers=ch.swisstopo.zeitreihen,ch.bfs.gebaeude_wohnungs_register,ch.bafu.wrz-wildruhezonen_portal,ch.swisstopo.swisstlm3d-wanderwege,ch.swisstopo.fixpunkte-agnes&layers_visibility=false,true,false,false,true&layers_timestamp=18641231,,,,&mobile=false&lon=7.22525&lat=46.02489&elevation=21326&heading=36.935&pitch=-25.081) with wohnungsregister layer.

**Comment by gjn** [comment]
We support voidLayer in 3D.

**Comment by oterral** [comment]
It doesn't work in some case :  

1) Go to https://mf-geoadmin3.dev.bgdi.ch/?dev3d=true
2) Wait Cesium to be loaded
3) Switch to voidLayer background 
4) Active 3d

-----> Pixelkarte is displayed

Expected:

No layer displayed.

**Comment by gjn** [comment]
Yes. Very early we had voidLayer fully supported in 3D, but then added this behaviour because of white-only screen. But we want it back.

**Comment by gjn** [comment]
This is actually quite an interesting bug that affects only backgroundlayers, because our backgroundlayers a) are layer groups and b) have a special 3d configuration (see https://github.com/geoadmin/mf-geoadmin3/blob/master/src/components/map/MapService.js#L987). When adding the layer to the ol map (via background selector), the synchronisation correctly adds the swisstlm3d map as defined in the above link. For that, it passes the `getCesiumImageryProvider` where it gets the information about the 3d layer configuration. The point: it uses the 3d sublayerids layer name(s) as keys inside ol3cesium to keep track of layers.

When removing the layer (via the background selector, go to voidlayer), the synchronisation inside ol3cesium only looks at the ollayer name,  detects a group and tries to remove the sublayers of this group as defined in the original config. But it doesn't know that this layer actually is stored with the 3d specific key. So the cesium layer actually remains in cesium.

This actually means that whenever you go back and forth between voidlayer and pixelkarte in the background selector, you add a siwsstlm3d to the cesium view - and they stay there forever. ...And it slows down the application considerably, because it downloads each tile mutliple times...

@gberaudo @oterral Easily reproducable bug.

**Comment by gberaudo** [comment]
Looking into it.

**Comment by gberaudo** [comment]
OL3-Cesium fix in https://github.com/geoadmin/mf-geoadmin3/issues/2837

**Comment by gjn** [comment]
Great. Thanks alot @gberaudo .
