### ISSUE TITLE
when public transport station is selected in swisssearch result load ch.bav.haltestellen-oev layer

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#2894]
"when public transport station is selected in swisssearch result load ch.bav.haltestellen-oev layer "

@Gjin how to solve this?

**Comment by gjn** [comment]
Just adding the layer? Or pointing to the selected object?

If the first: it would be a hack specifically for this kind of location data. We would need to have this type in sphinx index (maybe it already is).

For 2: we would need to assure that we actually have the same data and to have the object id. This would need major changes in back-end for the search indices. But I't maybe worth the pain because I think we will go in this direction for other kinds of data. We would need to assure to have same data source for same kind of data.

**Comment by davidoesch** [comment]
adding the alyer and point to the object (it has a stable id)
-> this is a major change in backend. In the far future  we will more data like this--- it is actaully linked data approch. thoughts on using SPARQL to drive SPHINX or actually the swisssearch service directly?

**Comment by gjn** [comment]
It's just about sphinx index creation. We need to assure that for this kind of data, the datasource is the same as for the actual layer. We can do 1) quickly.

For 2), I'll need to discuss this with several players.

**Comment by gjn** [comment]
I just checked, we need to add this information (type of result) to the sphinx index. I create an issue there.

**Comment by gjn** [comment]
https://github.com/geoadmin/service-sphinxsearch/issues/281

**Comment by boecklic** [comment]
relation between haltekante and didok of SBB/BAV haltestelle and TLM has to exist to be able to solve this issue
