### ISSUE TITLE
Print  report link for  ch.kantone.cadastralwebmap-farbe

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#2948]
For ch.kantone.cadastralwebmap-farbe ( ad  alter for a pure AV layer to be intgerated)
realize in the tooltip a link to a PDF

![unbenannt](https://cloud.githubusercontent.com/assets/4577727/11468735/25e1498e-9752-11e5-891f-8a6efd929db5.PNG)

The link to PDF is called
with the following paramteres
URL: https://geodata01.admin.ch/order/product.igs?product=av_pdf&pos=<Ost>/<Nord>
Resulat:
URL auf Resultatdatei

Mit der oben angegebenen URL kann ein PDF Plan A4 vom GeoShop
bezogen werden. User und Password müssen mit HTTP Basic Authentication
übergeben werden. Der GeoShop berechnet automatisch die betroffene
Parzelle und die optimale Skalierung für den Plan. Die Koordinate 
<Ost>/<Nord> muss im Koordinatensystem LV03 angegeben werden. 

Als Resultat des Aufrufs wird die URL des Resultatdatei zurück gegeben.
Die Resultatdatei ist erst ein paar Minuten nach Aufruf verfügbar. D.h.
die aufrufende Applikation muss bei der Abfrage den HTTP Status 
auf "200 OK" prüfen.

Create an expert tootlip based on the link above with a countdown set to 10 minutes. 

![unbenannt1](https://cloud.githubusercontent.com/assets/4577727/11480602/902b087a-9798-11e5-83d0-8f5796b2a4d5.PNG)

Every minute do a poll to see if file exist, if file existthen change the countdown to the download link

![unbenannt](https://cloud.githubusercontent.com/assets/4577727/11480610/98669888-9798-11e5-9b66-6e02d7ddb201.PNG)

**Comment by davidoesch** [comment]
@cedricmoullet  double check please

**Comment by gjn** [comment]
I think we need to pass by a service, because we can't directly pass HTTP Basic Auth from the browser without it being visible in the console.

**Comment by davidoesch** [comment]
It is opendata ...., but still you are right: bad practice

**Comment by cedricmoullet** [comment]
I already mentionned it to customer: we will not send credentials, it's a non sense.

**Comment by davidoesch** [comment]
@pfanguin : status update?

**Comment by gjn** [comment]
@davidoesch political discussion friday, ok?

**Comment by davidoesch** [comment]
awaiting feedback from germann

**Comment by davidoesch** [comment]
update per mail to @gjn

**Comment by davidoesch** [comment]
issue:
-> we don't know if the file exist ( for the first time extraction)
->  no parameter is send by  https://geodata01.admin.ch/order/product.igs?product=av_pdf&pos=/ regarding the existence of the file

Currenty no loading sign etc is implemented, but a refresh (f5) is necessary to see the file

@gjn : can you review here with @pfanguin ( json or pyhton solution)

**Comment by procrastinatio** [comment]
Small remarque:
- Is file generated every time, because you get a different file id for every requests:
```
$ curl http://geodata01.admin.ch/order/jPqrueQazrt/av_pdf.igs?pos=692381/195821
http://geodata01.admin.ch/download/273730342988832/egris_cadastre.pdf
$ curl http://geodata01.admin.ch/order/jPqrueQazrt/av_pdf.igs?pos=692381/195821
http://geodata01.admin.ch/download/406758629784142/egris_cadastre.pdf
$ curl http://geodata01.admin.ch/order/jPqrueQazrt/av_pdf.igs?pos=692381/195821
http://geodata01.admin.ch/download/63734651939177/egris_cadastre.pdf```
- Progress: no information is sent back by the server
- Basic Auth: What ressource must be protected ? The tooltips, the "print service" or the generated PDF ? The latter would make sense, the rest requires managing credentials in map.geo.admin.ch For now, it seems fully opened.
- The service is *very* minimal: you only get a `no object found` error, even if a canton is not covered at all.

**Comment by gjn** [comment]
The service is fully opened for us only.

Yes, service is not ideal. But we have 3 responses that we can work with:

1) not found (returned when pdf/service is not yet finished)
2) no object (returned when service is finsished but no pdf exists for this location)
3) pdf file (returned when pdf is created for this position).

The idea is to poll 1) for a reasonable amount of time in the back-end (500ms? 1000ms? 2000ms?) and the fill the link of the mako according to 2) and 3).

Font-end polling in simple html popup is not good, because it would require javascript injection in a simple html popup, and we should avoid that.

**Comment by davidoesch** [comment]
Hi @gjn @pfanguin 

The go live date here: 27.4 since it will be used for conference. can you confirm this date

**Comment by procrastinatio** [comment]
@gjn What is the point of polling for a few millisecond  before rendering the mako ?
- If it is < 1000ms, it is useless because the user needs already more than 1 sec to find and  click on the PDF link
- If it is > 1000ms the tooltip is not very reactive, the user will keep clicking on the feature
And if the mako is rendered at the timeout, the user only get "Your PDF **may** be **not** ready"

The only viable alternative, is to have an extended tooltip acting as a proxy for the download, with full JS spinner, etc. This service send back the PDF when ready or displays a spinner as long as it is not. But this is really to overcome the userfriendlyness shortcomings of the original service, which is really not the goal of mf-chsdi3.

**Comment by gjn** [comment]
Yes, if pdf creation takes this long, then front-end polling is only option.

**Comment by gjn** [comment]
How is it done in geoshop? Is it possible to see this directly in geoshop?

**Comment by davidoesch** [comment]
kontakt patrick ibele or beat tschanz for the acces to the sixgroup solution

**Comment by davidoesch** [comment]
current iimp
https://mf-geoadmin3.dev.bgdi.ch/ltfap/?topic=ech&lang=de&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=ch.kantone.cadastralwebmap-farbe&X=204768.79&Y=680417.55&zoom=9 

to fix
- [ ] PDF text is to big
- [ ] loading icons are not centered 
- [x] name the link "Plan für das Grundbuch"

**Comment by loicgasser** [comment]
https://github.com/geoadmin/mf-chsdi3/pull/2327
