### ISSUE TITLE
touch sensitivity for tooltips in 3D

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#3011]
all iOS and Android touch devices
Add swisismage 
go 3d
zoom in and pan around

result
- the tooltip is activated event a very short touch 

-> extend the touch and hold timer

**Comment by davidoesch** [comment]
it is now even worse with having tooltips even if there is no geometry. 3D is barely not usable now 
IMHO: set tooltip with no tooltip info only if if there is a layer which has tooltips an user clicks on a feature with no tooltips.
@gjn @cedricmoullet : your thoughts?

**Comment by oterral** [comment]
@davidoesch can you try this [branch](https://mf-geoadmin3.dev.bgdi.ch/teo_touch/?topic=swisstopo&lang=fr&bgLayer=voidLayer&lon=8.27176&lat=47.80959&elevation=19532&heading=175.237&pitch=-20.012&layers=ch.swisstopo.swissimage-product)

There is a left click triggered after nearly each pinch action, thios branch try to fix this.

**Comment by davidoesch** [comment]
Better but on mobile and desktop : double click user expect s zoom or am I wrong @gjin

**Comment by gjn** [comment]
Yes, I would agree.

**Comment by cedricmoullet** [comment]
This branch works very well in 2.5D on my iPhone 6. But:
1. The position dialog doesn't work in 2.5D (long touch) ( this never
worked AFAIK)
2. The tooltip doesn't work in 2D.
3. It's needed to click twice on the position dialog in order to close it


2016-01-29 7:26 GMT+01:00 Gilbert Jeiziner <notifications@github.com>:

> Yes, I would agree.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geoadmin/mf-geoadmin3/issues/3011#issuecomment-176600054>
> .
>



-- 
Twitter: http://twitter.com/cedricmoullet
Linked In: http://www.linkedin.com/in/cedricmoullet

<http://twitter.com/cedricmoullet>

**Comment by oterral** [comment]
1. Yes it's deactivated in 3d
2. I think you found a bug in prod, I investigate then redeploy if necessary.
3. Strange will fix that.

**Comment by davidoesch** [comment]
Position button is deactivated as designed. Sensitivity is now OK
