### ISSUE TITLE
Don't load opaque layers

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#3019]
- [ ] order layer according to transparency setting 
- [ ] opaque layers are added the bottom
- [ ] only the top opaque layer is loaded, the others not (as in 3D)
- [ ] opacity setting is managed in BOD (as it is currently done for some vector layers)

**Comment by gjn** [comment]
First, please read comments by @ltclm here: https://github.com/geoadmin/mf-chsdi3/issues/1821

It's not only about opaque property, but also about the extent of that layer. Some are well outside Switzerland (pixelkarte-farbe), some are kind of outside of Switzerland (swissimage-product), some are exactly Switzerland (zipcodes). This is not easy to handle with a single attribute. (That's mainly a problem for point 3 above - which I don't think is easily possible without loosing something)

Also, I don't you think this handling of the layermanager via an (almost) invisible value will look like black magic to the users? What happens if user changes the opacity? Does layermanager auto-rearrange? If not, does it do it after layer is added?

Would like to discuss this.

**Comment by ltclm** [comment]
Yes we should discuss this. Point 1 and 2, 4: we could add something like a z-value to each layer representing its relative position in the layer tree? Point 3: i would not do something like that at all in 2d: see https://github.com/geoadmin/mf-chsdi3/issues/1821

**Comment by davidoesch** [comment]
Let's keep its simple

There are two user scenarios

A) search and add a layer:
expected result: layer with data is shown,independent from what is already selected
current solution: added layer is always on the top, fully opaque vector layers are *always* set to opacity=0.7
current result: user get what he wants


B) complex single topic map ( like tick maps)
Expected result: user opens a preconfigured layer ,highly customized regaridng order and opacity
current solution: experts can provide a permalink 
current result: user gets what he wants https://s.geo.admin.ch/68f9247e2c 


Conclusio: don't pantronise the user with automated settings. give him the right tools to to what he wants. the issue is the ordering of the layer is currenttly no that easy, but a ticket for this is open: keep the title open

So : don't bring to much logic into this. IMHO close the ticket

**Comment by gjn** [comment]
Also, we will have easy ordering of layers via drag & drop soon, which should facilitate things for the user.
