### ISSUE TITLE
Infobox "Link für Datenbezug"

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#3022]
In Infobox "Link für Datenbezug"

if BOD and geocat is empty for this field  

Result:
link to current permalink is set

Expected result:
no link is set in this case "-"

**Comment by ltclm** [comment]
The issue comes from empty strings from the geocat data. 
This change of the layer info views in the bod will fix this by replacing empty strings with NULL.
https://github.com/geoadmin/db/commit/b43ec287fe3c4e55ea87695db4d2cb7a31561c94

dev:
https://mf-chsdi3.dev.bgdi.ch/rest/services/all/MapServer/ch.bafu.moose/legend?lang=de
prod:
https://mf-chsdi3.prod.bgdi.ch/rest/services/all/MapServer/ch.bafu.moose/legend?lang=de

**Comment by gjn** [comment]
This will be fixed on next deploy. Thanks alot @ltclm
