### ISSUE TITLE
obstacle: inactive elements are visible

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#3048]
reproduce

load
https://map.geo.admin.ch/?topic=aviation&lang=de&bgLayer=ch.swisstopo.pixelkarte-grau&layers=ch.swisstopo.zeitreihen,ch.bfs.gebaeude_wohnungs_register,ch.bafu.wrz-wildruhezonen_portal,ch.swisstopo.swisstlm3d-wanderwege,ch.bazl.luftfahrthindernis&layers_visibility=false,false,false,false,true&layers_timestamp=18641231,,,,&catalogNodes=1379,1381,1514&X=137223.39&Y=694249.54&zoom=10

click nearby
8.66673, 46.38002

-> suddenly inactive obstacle are visible
![unbenannt](https://cloud.githubusercontent.com/assets/4577727/12353856/28d9418c-bb92-11e5-91cf-1317fb2bc5a1.PNG)

should not be the cas

**Comment by ltclm** [comment]
luftfahrthindernis objects from the database should be filtered 
```
WHERE abortionaccomplished IS NULL 
```
We have to create a view and update the chsdi model to do that. I will prepare a pr

**Comment by ltclm** [comment]
As discussed with @davidoesch 

**now:**

layer|WMS|chsdi model|identify|query tool
------|-------|---------|-----|-------
ch.bazl.luftfahrthindernis|active|inactive and active|inactive and active|test

**future:**

layer|WMS|chsdi model|identify|query tool
------|-------|---------|-----|-------
ch.bazl.luftfahrthindernis|active|active|artive|active
ch.bazl.luftfahrthindernis_deaktiviert|inactive|inactive|inartive|inactive

we should get rid of the inactive objects for the official layer and integrate a new layer with inactive objects. 

@mariokeusen  we should have the confirmation of the data owner that we can remove the inactive objects from the current data integration scripts and then integrate a new layer with inactive objects only.

**Comment by mariokeusen** [comment]
The current behaviour is exactly the customer's intention, because there are predefined queries/usecases where the inactive obstacles are absolutely needed. Therefore we basically decided (that was back in 2012) to integrate active and inactive obstacles into the same layer and the customer accepted the risk, that inactive records are available on tooltips, if you click at the right/wrong place in the map.

If we wanna propose alternatives like described by @ltclm, I'll first have to discuss that with the customer. In second consequence, a new Abnahmeprotocol would be needed.

Therefore: leave as is for now!

**Comment by davidoesch** [comment]
Hallo Mario the customer wants to change this behavior (meeting feedback from Friday) since it is dangerous that he click s on a outdated obstacle

**Comment by davidoesch** [comment]
Get in touch with richiger

**Comment by mariokeusen** [comment]
As discussed: waiting for the customer coming with a concrete change request, resp. new-integration of data.

**Comment by oterral** [comment]
So since it's a data integration issue. Can we close this ?

**Comment by davidoesch** [comment]
Yep, referenced it in: https://jira.swisstopo.ch/browse/BGDIDI_KB-872
