### ISSUE TITLE
Geometry label inside of geometry

### ISSUE THREAD

**Issue by dcustode** [geoadmin/mf-geoadmin3#3051]
It would be helpfull to have a funtionality that allows to place the label of a geometry inside the geometry, so that there want be any collisons with labels of neighbour geometries.

![image](https://cloud.githubusercontent.com/assets/16756994/12389264/f1424a28-bdd7-11e5-8397-592766978333.png)

**Comment by davidoesch** [comment]
Mapserver configuration or / and dataintegration  issue

**Comment by ltclm** [comment]
@dcustode which layer is on your screenshot? Could you share a permalink?

**Comment by dcustode** [comment]
http://gdwhraster/GdwhRasterExport/DatasetDetail?gdsKey=PK100_LV03 on tab Releases. Choose Release 2012. LG

**Comment by ltclm** [comment]
so it is a kml label issue 
@oterral do you think it is possible to solve this?

**Comment by gjn** [comment]
kml? which kml is this?

**Comment by oterral** [comment]
I tought your problem was in map.ge.admin.ch. Maybe it's not the good place to discuss about this.

Right now the only solution I see is to use the [getInteriorPoint function](http://openlayers.org/en/master/apidoc/ol.geom.Polygon.html#getInteriorPoint)

You should create another feature with the point returned by this function and apply the text style on it.

**Comment by oterral** [comment]
@dcustode  did you succeed ?

**Comment by oterral** [comment]
I close this issue since it's not related to mg-geoadmin
