### ISSUE TITLE
Tooltip does not appear when  mouse hand is active

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#3065]
All Os All Browsers desktop

open https://s.geo.admin.ch/698ea0f840

position mouse on the left border of the left blue stop icon

mouse pointer turn to "hand"

click: result
![unbenannt](https://cloud.githubusercontent.com/assets/4577727/12475080/83928efc-c020-11e5-843d-1bc1bb3cf45c.PNG)

-> no tooltip is shown (no info available)

Expected result:
If the mouse pointer turns into a hand and user clicks: the tooltip is shown

**Comment by oterral** [comment]
That's exactly why we add a no toolitp information. It's a client side detection, so I see 2 solutions:

- put in the layersconfig a tolerance value (could be the size of the icon)  different for each layers.
- leave as it is

**Comment by gjn** [comment]
We added the no info popup exactly for that: https://github.com/geoadmin/mf-geoadmin3/pull/2865

Discussion about the pixel detection and tolerance is here: https://github.com/geoadmin/mf-geoadmin3/issues/2942

**Comment by davidoesch** [comment]
#2865 and #2942

-> but the why not add the handsize tolerance a s tootlip tolerance ( i know this is related to the geometry) but this is what users expect. use the geometry has handtrigger  as well

**Comment by gjn** [comment]
Can't imagine how this could be done using current per-pixel approach. It's not easy to apply tolerance here, because we don't know the geometry of a feature. we only have the pixels of the feature. So I think the current per-pixel approach to trigger cursor change does not work.

As @oterral said, we have the possiblity to add a tolerance value per layer. This could be adapted for the layers only we deem worthy. Note however that this will not be perfect as well (square symbols) and might still result in false negatives. We would actually need 2 values, as mobile is a different beast altogether...and retina displays still another beast.

There's no perfect, work-for-all solution. Even if we would use UTFGrid for each layer.

The only workable solution is really vector layers / vector tiles. I propose to focus are efforts on this and merge important layers to this.

**Comment by loicgasser** [comment]
All that being said, it really weird that we miss some stations. @pfanguin It seems to me that the stations table has been updated and WMTS and geometries don't match anymore. All the stations that are is this layer should be clickable and it's not tooltip/tolerance issue.

**Comment by loicgasser** [comment]
If stations are likely to change all the time we should maybe switch to WMS.

**Comment by davidoesch** [comment]
station switch twice a year (Fahrplanwechsel)
@loicgasser can you provide examples where this issue occurs? we need to confront the dataowner with this

**Comment by gjn** [comment]
@davidoesch Good to close this and wait on vector tiles?

**Comment by davidoesch** [comment]
what about the s3 approach?

**Comment by gjn** [comment]
You mean utfgrid? For all layers? Only for selected layers?

**Comment by davidoesch** [comment]
For all layers / utfgrid. Other possibility for layers which consist of different geometries/not one single symbol: create a feature highlight geometry layer which corresponds with the outline of the symbols.

**Comment by gjn** [comment]
I don't understand the second option. How would we use that on front-side? Query back-end on every mouse move?

UTFGrid will impact performance on client as for every raster layers, we would need to have utfgrid data loaded.

**Comment by davidoesch** [comment]
Same procedure as for geocover : https://s.geo.admin.ch/6aa97e4efc

**Comment by gjn** [comment]
I don't think I understand. The mouse is correct because the raster has pixel information everywhere (as all full coverage layers have). This kind of layers are not the problem.

We have troubles with Gebäude Register, Haltestellen, IVS Routen, etc. (points, polylines mainly).

**Comment by davidoesch** [comment]
Let's solve this with vector tiles...

**Comment by gjn** [comment]
ok. I close this for now.
