### ISSUE TITLE
3d tooltip without geometry

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#3070]
Android open
https://s.geo.admin.ch/69914b3b00
Click on the middle of the lake
Result : tooltip appears with a link to a route which is not there

**Comment by oterral** [comment]
The route is there : https://map.geo.admin.ch/?ch.astra.wanderland=7.07&lang=de&topic=ech&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=ch.astra.wanderland,ch.swisstopo.zeitreihen,ch.bfs.gebaeude_wohnungs_register,ch.bafu.wrz-wildruhezonen_portal,ch.swisstopo.swisstlm3d-wanderwege&layers_visibility=true,false,false,false,false&layers_timestamp=,18641231,,,&X=201740.00&Y=687560.00&zoom=5

But because of this [bug](https://github.com/geoadmin/mf-geoadmin3/issues/2715) on Cesium polyline line are not displayed on top of terrain.
