### ISSUE TITLE
graticule selection: add WGS84 and LV95 as checkbox

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#3219]
With WGS84 and LV95 as dedicated layer [1] in the viewer we give the user now the options to choose in the viewer the layers
between 2 graticules instead of the combination
[1] org.epsg.grid_4326 https://redmine.prod.bgdi.ch/issues/4269 
 org.epsg.grid_2056 https://redmine.prod.bgdi.ch/issues/4740 

Change UI so the Coord grid selection adds now only Lv95

cc @mariokeusen

**Comment by cedricmoullet** [comment]
I would not add a checkbox, but document in the help how to do that with wms. It doesn't seems to be a feature requested by the majority...

Envoyé de mon iPhone

**Comment by davidoesch** [comment]
it was a feature request. imho we can just stitch to lv95 grid. 
the proper solution would be to have it in the pdf as tick marks on th edge of the map as defined in the original spec for re3....

**Comment by AFoletti** [comment]
now that the grids are (will be) standard layers, a special print setting should no more be needed.
+1 for Cedric's suggestion: document the grids in the help and let the user build his map with the grid as a layer in order to have it printed out

If we really need a print setting, I suggest we stick with lv95 only

**Comment by davidoesch** [comment]
Stick to lv95 only

**Comment by AFoletti** [comment]
wil be fixed on prod with next deploy
