### ISSUE TITLE
Location marker of search selection

### ISSUE THREAD

**Issue by gjn** [geoadmin/mf-geoadmin3#3349]
The location marker after search collection does not work for all results.

Search 'ta' and select the first result (Tägertschi), it zooms to correct location, but there is no marker. In the hover preview for this entry, the marker is visible.

For the 2nd result (Tavannes), there is the hover preview marker and when selecting the element, map zooms correctly and marker is there. 

I've looked at [raw search results](https://api3.geo.admin.ch/1464793988/rest/services/ech/SearchServer?searchText=ta&lang=de&type=locations) and they look the same to me.

Also, not all results have preview marker.

**Comment by oterral** [comment]
The reason is if the extent of the feature makes the map zooms on zoom 7 or lower, the marker is not displayed.

Tavannes makes the map zoom on zoom 6 and Tagertschi on zoom 7

See https://github.com/geoadmin/mf-geoadmin3/blob/master/src/components/MarkerOverlayService.js#L48

Should we remove this limitation ?
