### ISSUE TITLE
Discussion: layersConfig/topics on build

### ISSUE THREAD

**Issue by gjn** [geoadmin/mf-geoadmin3#3357]
I put this up for discussion, because I think current build system as a little flaw.

Currently, during build, we curl the defined back-end to have a) the topics definition and b) the layersConfig. We did this because appcache needs those resources under the same domain as the application. Previously, this was solved by having a rewrite rule on apache level. We can't use this because we want to move the app to S3.

An alternative would be to actively track the layersConfig/topics inside the mf-geoadmin3 project. Downside of this would be that it needs to be updated by hand (via PR) everytime.

Are there other possibilities?

ping @loicgasser @procrastinatio @oterral

**Comment by procrastinatio** [comment]
My approach was 1/ to use a static file for 'release' and the apache proxy for 'debug' 2/ Use service name which a complete file name eg. config.de.js instead of 'config?lang=fr'

But the main issue is that nothing in the DB is versionned. The DB `bod_dev`from tody is not the `bod_dev`from tomorrow, and it may break many things at all level. I would be in favour of using version/tag name for DB instead of `dev`, `int`, prod` which mean nothing.
When developping code, I expect all DB but `master`to be in a usable/production state.

**Comment by gjn** [comment]
I agree. That's why we'll have a new bod development process soon (ping @loicgasser and @ltclm ).

**Comment by loicgasser** [comment]
@procrastinatio see https://github.com/geoadmin/dbmanagement
