### ISSUE TITLE
swisssearch: name in LK25 but not in lk10

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#3394]
search for "burgbachstäg"

select "Road Burgbachstäg (BE) - Schwarzenburg,Rüeggisberg"

result:
map zooms to lk10 https://s.geo.admin.ch/6cfeb76467 the text is not visible

expected result
map zooms to:  lk25 https://s.geo.admin.ch/6cfeb7f61c 

so if the name is not in lk10: zoom to lk25

**Comment by ltclm** [comment]
the default recenter zoom for gazetteer objects is zoomlevel 10 (=lk10) [1]. So features with a small extent like 'burgbachstäg' will be recentered to lk10 zoomlevel. Features with a bigger extent will be recentered to the feature extent zoomlevel. We had the same behaviour with the tlm before. The service response has no information about zoomlevel [2]

[1] https://github.com/geoadmin/mf-geoadmin3/blob/febce145bef4d99956132a3a6ac6371fd5c848c8/src/components/search/SearchTypesDirectives.js#L19

[2] https://api3.geo.admin.ch/rest/services/ech/SearchServer?searchText=burgbachst%C3%A4g&lang=de&type=locations

**Comment by gjn** [comment]
Do we know at any stage, which gazetteer object is on what map? (Lk10, Lk25, etc)

**Comment by ltclm** [comment]
neither swissnames3d nor lk10 annotation data has this information. 
zoomlevel/product information has been removed from the names dataset during the introduction of tlm.

**Comment by gjn** [comment]
Unless we have this information, I can't see how we could do the desired behaviour in a consistent manner. It'll be always tweak right, tweak left.

This need to be discussed once again with the data provider.

**Comment by davidoesch** [comment]
We have to wait for dkm 25 50.... but meanwhile I suggest: if searchterm is not in lk10 , then zoom to pk25

**Comment by gjn** [comment]
The issue is: we don't know if a search term is on lk10 or not.

**Comment by davidoesch** [comment]
@ltclm : Correct me if I'm wrong: lk10 is delivered with a complete list of all names on it. This was the key purpose of the session we made with karto/topo

**Comment by ltclm** [comment]
Yes, we have a complete list of lk10 features. But as the service is designed right know, we dont have any attribute in the result which can be used to choose the zoomlevel. The only attribute which can be used for now is the feature geometry / bbox.
The **gazetteer index** has a mixture of **lk10 features** and **not lk10 features** with a default recenter zoomlevel lk10. That's all we know about this data concerning source zoomlevel. For the second group we still wont know if they are on lk25, lk50, ...
So we would have to introduce **one hack more** and increase the feature geometry bbox of points, lines, polys of the **not lk10 features** so that won't be recentered to lk10 anymore, :-1: .

@gjn It would be probably better to introduce a new attribute in the sphinx index and the service response with the feature zoomlevel, which can be used in the frontend for the recentering. When we have the full data (lk10,lk25,...,lk1000) with zoomlevel information we will have to do that anyway. For know this attribute will be ``lk25`` for everything which is not in the lk10 list.

**Comment by gjn** [comment]
I think it makes sense to add a new attribute, yes.

But I'm not sure it will cover all uses cases. I think there will be names that we take from **not lk10 features** data source (so attribute is NOT lk10) that actually _is_ on lk10 and should be zoomed on lk10.

**Comment by davidoesch** [comment]
Since we have to add a new attribute to take into account future  DKM features -- +1 for adding a new attribute

**Comment by gjn** [comment]
https://github.com/geoadmin/service-sphinxsearch/issues/281

**Comment by gjn** [comment]
sphinx pr is ready.

**Comment by loicgasser** [comment]
@gjn Can we close that?

**Comment by gjn** [comment]
Yes.
