### ISSUE TITLE
ch.bazl.luftfahrthindernis : Attribute search does not work 

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#3485]
All OS ALL DEVICES
reproduce
start
https://map.geo.admin.ch/?topic=aviation&lang=de&bgLayer=ch.swisstopo.pixelkarte-grau&layers=ch.bazl.luftfahrthindernis&catalogNodes=1379,1381,1514&X=104891.03&Y=661095.59&zoom=2

search for  a register ID eg 256-HL-30078

Result
Searched ID and result do not match

![image](https://cloud.githubusercontent.com/assets/4577727/18385685/65ae8bb0-7692-11e6-8016-59a9ea664cac.png)

cc @mariokeusen

**Comment by davidoesch** [comment]
might be a side effect of https://github.com/geoadmin/mf-chsdi3/pull/2222#issuecomment-245614777 ?
 ping @loicgasser

**Comment by davidoesch** [comment]
confirmed: it is a side effect of geoadmin/mf-chsdi3#2222  attribute search is messed up
@ltclm @ltgal can you give here an ETA for the fix?

**Comment by ltclm** [comment]
i can confirm that it is not a side effect of https://github.com/geoadmin/mf-chsdi3/pull/2222 .
due to the sachplan publication last week and some structural changes in the uvek database we had to deploy the whole database uvek exactly at the right moment. to do that we have decided to deploy the database withouth sphinx trigger.
The feature ids in sphinx do not match anymore the feature ids in the database.
we will have to rebuild the sphinx indices of uvek database.

**Comment by ltclm** [comment]
sphinx index ch.bazl.luftfahrthindernis has been rebuilt.
It is working again.

**Comment by davidoesch** [comment]
Customer informed

**Comment by pfanguin** [comment]
See : https://github.com/geoadmin/service-sphinxsearch/pull/295
