### ISSUE TITLE
Improve hiking time accuracy

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#3492]
Situation
- A) only 200 points per KML line are taken into account calculate the hiking time 
- B) Hiking time  formula is adapted to work with 200 points and not every vertex
  Results: For situation with long tracks and steep segments: time can be wrong 
  See
  -Customer feedback ID : 2016091722503037
- @mariavkourouni  study  with the testtracks

we have serious issue: the same track gives different results now in map.wanderland and map.geo.admin.ch. as confirmed by camptocamp: schweizmobil uses the same formula as described in https://github.com/geoadmin/mf-geoadmin3/blob/d521ff6a0726a47aaa85bfdee30b5b288eca2b0a/src/components/profile/ProfileService.js line 205ff

Steps to reproduce:

Draw line in wanderland https://map.wanderland.ch/?lang=en&bgLayer=pk&resolution=50&X=630698&Y=208463&layers=Wanderland&trackId=3181986 
Hiking time: 9h 40min
export to gpx (250 waypoints) in settings, convert via gpx2kml

[langnau_huttwil.zip](https://github.com/geoadmin/mf-geoadmin3/files/606499/langnau_huttwil.zip)

Import KML into map.geo.admin.ch
Hiking time :8h19min 

I'm quite sure that the results on launch of hiking time were both the same for the same GPX /KML in map.geo.admin.ch and map.wanderland.ch we did some massive testing when we launched this feature
Task:
- improve the accuracy to fit the official formula

Action:
- increase the smaple rate - ideally to represents the swissalti3D completely or  80/20 to increase it adaptively to keep cost low and performance high
- if we have full resolution of profile: adapt the formula to use the original wander.ch formula (25% rule)

Result:
Even extreme tracks as in @mariavkourouni testbook and the Customer ID above are correct

**Comment by procrastinatio** [comment]
For reference, customer's original [KML](https://www.procrastinatio.org/kml/wrong_profile.kml) and the same, as [GeoJSON](https://www.procrastinatio.org/kml/wrong_profile_with_altitude.geojson) with altitude points attributed.

The original KML has 168 points for a distance of about 18.8 km. If for every points of the original file, we get an altitude, the result is given as **original**. If we use the profile service, with the same original geometry, but with more points, we get the following results:

Points |  D+ (m) | D- (m) | Max (m) | Min (m)
-------|----------|---------|----------|--------
original| 2218.6 | -1277.7  | 2279.6 | 1320.5
200 | 1571.1 | -625.5  | 2258.9  | 1317.5
500 | 1866.8 | - 920.1 | 2262.5  | 1311.6
1'000 | 2078.1 | -1130.8 | 2268.7 | 1307.5
10'000 | 2739.3 | -1702.3 | 2268.6 | 1304.1
50'000 | 3676.5 | -2729.6 | 2269.2 | 1304.4

So clearly, _brut-forcing_ adding more points is not a good idea (excluding a big bug in the profile service). 

A better approach would be to detect the inflection point of the profile, and use them:

![profile3](https://cloud.githubusercontent.com/assets/1236739/19143746/257a3e80-8ba6-11e6-8a4b-3f6c5ea49c81.png)

**Comment by loicgasser** [comment]
I can only agree with @procrastinatio, better change the re-sampling approach of our profile points, or interpolate differently to try to detect those bumps and holes than add more points.

**Comment by gjn** [comment]
To detect the bumps, you need to have more points, you can't guess in the void. Having more poitns would be be performance issue then.

Maybe we let the user choose direclty the precision/number of points he wants in the UI - and he could then be made aware of the performance impact.

I consider this a special case (in mountains where DTM is extremely heterogene). We should not special cases impact our overall approach and performance.

**Comment by gjn** [comment]
Maybe a simple switch would be enough:
- Take original: all points of the original line is taken. If it's alot of points, then it will be slow but precise
- Take 200 sampling: as we do now, which suffers precision (would be default as well)

**Comment by procrastinatio** [comment]
@gjn @loicgasser Maybe you want to check https://github.com/geoadmin/service-alti/pull/12

**Comment by procrastinatio** [comment]
This use case, a footpath on a ridge or along a steep slope is really challenging: a small error in position, and you introduce unecessary altitude changes (traversing footpath are normally more or less even, if possible)

**Comment by davidoesch** [comment]
we have serious issue: the same track gives different results now in map.wanderland and map.geo.admin.ch. as confirmed by camptocamp: schweizmobil uses the same formula as described in https://github.com/geoadmin/mf-geoadmin3/blob/d521ff6a0726a47aaa85bfdee30b5b288eca2b0a/src/components/profile/ProfileService.js line 205ff

Steps to reproduce:

Draw line in wanderland https://map.wanderland.ch/?lang=en&bgLayer=pk&resolution=50&X=630698&Y=208463&layers=Wanderland&trackId=3181986 
Hiking time: 9h 40min
export to gpx (250 waypoints) in settings, convert via gpx2kml

[langnau_huttwil.zip](https://github.com/geoadmin/mf-geoadmin3/files/606499/langnau_huttwil.zip)

Import KML into map.geo.admin.ch
Hiking time :8h19min 

I'm quite sure that the results on launch of hiking time were both the same for the same GPX /KML in map.geo.admin.ch and map.wanderland.ch we did some massive testing when we launched this feature

**Comment by procrastinatio** [comment]
[langnau_huttwil.kml](https://map.geo.admin.ch/?layers=KML%7C%7Chttps://public.geo.admin.ch/EP_a_ofCR3yzM472utwgAw)

Even the basis metrics are very different.

|   | wanderland  | geoadmin  |
|---|---|---|
| length [km]  | 32.67  | 32.16  |
| pos/neg [m] |1350/1380   | 777.30/809.7  |
| min/max [[m] |641/1326   |  643.4/1315 |
| time [h] | 9h40 | 8h19|

Is `wanderland.ch` using the same service as `map.geo.admin.ch` ? As stated above, the more points you use, the wrong it is, at least on these ridge footpath.

**Comment by davidoesch** [comment]
Same service same data same algorithm.

**Comment by fredj** [comment]
I don't know all the details but this loop looks suspicious:
https://github.com/geoadmin/mf-geoadmin3/blob/master/src/components/profile/ProfileService.js#L233-L235

`j` goes up to `15` but `arrConstants.length` is `16`

**Comment by fredj** [comment]
And the veloland implementation used the slope from -40% to +40%:
https://github.com/geoadmin/mf-geoadmin3/blob/master/src/components/profile/ProfileService.js#L229-L230

**Comment by davidoesch** [comment]
Hi Veloland uses according to Utiger:

A) Formula

```
    def walkingTime(self, l, h):
        if l == 0:
           return 0

        s = (h * 10) / l
        if s > -4 and s < 4:
            cs = [14.271,
                  3.6991,
                  2.5922,
                  -1.4384,
                  0.32105,
                  0.81542,
                  -0.090261,
                  -0.20757,
                  0.010192,
                  0.028588,
                  -0.00057466,
                  -0.0021842,
                  0.000015176,
                  0.000086894,
                  -0.00000013584,
                  -0.0000014026]
            mpk = 0
            i = 0
            for c in cs:
                mpk += c * pow(s, i)
                i += 1
        elif s > 0:
            mpk = 17 * s
        else:
            mpk = -9 * s
        return mpk * l / 1000
```

If I interpret the formula correctly, a constant value is set from +/- 40% (please check if my statement is correct).

Difference between map.geo.admin.ch
1. during the calculation of the hiking time from the TLM altitude information: the TLM has been simplified at SchweizMobil for licensing purposes - how is this done? can you  check on how they use our height service ?

2. Different parameters are used by schweizmobil when using the swisstopo web service: can you double check?

**Comment by oterral** [comment]
please verify the fredj comment

**Comment by davidoesch** [comment]
hmm who will verify it?

**Comment by oterral** [comment]
@procrastinatio

**Comment by procrastinatio** [comment]
OK, for now _profile service_ is broken everywhere...
1/ https://github.com/geoadmin/mf-geoadmin3/issues/3492#issuecomment-262773429 has no impact
2/ https://github.com/geoadmin/mf-geoadmin3/issues/3492#issuecomment-262787562 as a big impact, not suprinsing.

**Comment by martinutiger** [comment]
Thanks, I appreciate to let me in the discussion!
About map.wanderland.ch:
1. First, the formula noted by David is correct, we've got them from Urs Isenegger (our intentions was to make it the same as in SwissMap) - it is NOT the original formula from SwissHiking, which is published here: http://wandern.ch/download.php?id=265_984bc5d8
2. When drawing a track on map.wanderland.ch, there are two modes:
A) "Magnetic Routes":  "Magnetic Routes" is set by default, make sure you always click on a street. With "Magnetic Routes" on, the time computed is done on TLM vertex points. The TLM is simplified with FME Simplification to 2 meter (during preprocessing) due to licence reasons.
B) "Magnetic Routes off". Set "Magnetic Routes" off, then the swisstopo web service COMB will be used with 200 points (allways, not depending on the length of the track). The swisstopo web service will be used as well if Magnetic Routes are on, and you click not on a street.
3. For testing, don't use gpx-import or export, because it will allways be simplified. Better you use the webservice: https://map.schweizmobil.ch/track/<id>/show
The id is the track id, eg.
Test Tour Magnetic Route on:
https://map.schweizmobil.ch/?lang=en&bgLayer=pk&resolution=1.5&X=614047&Y=129836&trackId=3237504
https://map.schweizmobil.ch/track/3237504/show
In the json, there is an attribute "elevationmodels": "ElevationModel Snapped" - then the track is on TLM
Test Tour Magnetic Route off:
https://map.schweizmobil.ch/?lang=en&bgLayer=pk&resolution=1&X=614154&Y=129838&trackId=3237509
https://map.schweizmobil.ch/track/3237509/show
elevationmodels": "ElevationModel not snapped"
4. We would like to improve: 
A) use original TLM withouth simplification
B) use original hiking time formula
C) use swisstopo webservice with more or less than 200 points, depending on the track length (if this is the way to go)
Therefore we are highliy interested, what you will find out.
Thanks!
Martin
PS: and of course, feel free to ask me

**Comment by procrastinatio** [comment]
To summarize, btetween schweizmobil and geo.admin.ch, for a given line/path, we have Unterschied at two levels (see https://github.com/geoadmin/mf-geoadmin3/issues/3492#issuecomment-262305246)
* Basic data, like number of points, heights
* Hiking time formulas

**Comment by davidoesch** [comment]
The formula is the same, the Implementation is different

**Comment by procrastinatio** [comment]
@martinutiger OK, nice one. But this really a profile generation issue. The profile service will have to be rebuild to use 3D vector data.

Do we have access to wanderland code ?

**Comment by procrastinatio** [comment]
Comparison between profile data and march time for the very same route, between `wanderland` ([1] and [3]), using the map.geo.admin.ch formula @mariavkou but on height attributed individualy with `rest/service/height`, and `map.geo.admin.ch` ([2] and [4]), _i.e_ using `rest/service/profile.json`

For small profile, all three system are close, but when the number of points increase, `map.geo.admin.ch` differs.
So the issue is with the raw data (`rest/service/profile.json`), less with the _formulae_ (see https://github.com/geoadmin/mf-geoadmin3/issues/3492#issuecomment-251886284).


1/ First example (ca 130 points)


[1] https://map.wanderland.ch/?lang=fr&bgLayer=pk&resolution=5&X=606803&Y=157462&trackId=3243052

[2] https://map.geo.admin.ch?adminId=tibU3hn9SaKw5tsADZYf9A


|   | wanderland  | formula  | geo.admin.ch |
|---|---|---|-----|
| length [km]  | 4.73 | 4.73  |   4.72
| pos/neg [m] |1'132/1   | 1'132/-  | 1'1130/1
| min/max [[m] |1172/2303   | 1172.35/ 2303.17 | 1'1173/ 2'302 |
| time [min] | 190 | 195|  193  |



2/ Second example (656 points)

[3] https://map.wanderland.ch/?resolution=20&X=605855&Y=152911&trackId=3243373

[4] https.//map.geo.admin.ch?adminId=B9QIk14fQz6Q8GnQ7LZlgQ



|   | wanderland  | formula  |  geoadmin |
|---|---|---|----|
| length [km]  | 18.87|18.87 | 18.64 |
| pos/neg [m] |1'449/1'329  | 1'448/-  | 1'328/1'208 |
| min/max [[m] |1'229/2'387   | 1228.72/2387.39| 1'230/2'368  |
| time [min] | 443 | 447| 407  |

**Comment by martinutiger** [comment]
@procrastinatio 
I've attached the code here (sorry, took me some time to find it...):
[walking_time.txt](https://github.com/geoadmin/mf-geoadmin3/files/702269/walking_time.txt)

If you rather would like to have access directly, please tell me which user-name / e-mail

**Comment by davidoesch** [comment]
Just for the record: here the comparison study we did in q2 2016

[2016_04_13_Export_WL_Etappen.zip](https://github.com/geoadmin/mf-geoadmin3/files/703880/2016_04_13_Export_WL_Etappen.zip)
[Doc_evaluation_hiktime_maria.zip](https://github.com/geoadmin/mf-geoadmin3/files/703881/Doc_evaluation_hiktime_maria.zip)

**Comment by procrastinatio** [comment]
**Preliminary remarks**
* Acurate hiking time make sense only on road or track. Off beaten track, there are too many factors that may increase or deacrese walking time.

* map.geo.admin.ch should not allow download/export of vector data and/or altitude (really ?)

For wanderland, the easiest way is to compute a network datset, with all road, track, path suitable for walking, i.e. the `ch.swisstopo.swisstlm3d-wanderwege`plus a subset of the road network (no motorway for instance).

For map.geo.admin.ch, the approach is basically the same, but with trick to hide/protect the holly vector data, e.g. displaying the `maget route` as image (?), storing only `waypoints` and not the track itself, usw.

**Comment by gjn** [comment]
Since it was moved to 1st prio, what do we want?

**Comment by davidoesch** [comment]
Marc's last stated approach: for hiking layer data owner (astra and Swisstopo) need to add the hiking time into the geometries. Bovier is informed. But how to export a KML which does not contain the geometries of Swisstopo?

**Comment by procrastinatio** [comment]
@davidoesch are the geometry-less KML still relevant. Very soon, we'll have vector tiles, no ?
So, if I summarize, we should have improved hiking time, but not deliver the data used (geomtries snapped to footpath and heights), right ? So, we have to:
* For dispaly in map.geo.admin.ch, (see image) generate an image to highlight (green) the choosen footpath (red)
* For KML, store the calculated hiking metadata in the KML or a separate file, and probably the footpath segments used, e.g. _345-346-350-356-257_ 
For Schweizmobil, it would be easier, as the have none of the two limitations above.

![hiking](https://cloud.githubusercontent.com/assets/1236739/23463021/68389cf0-fe90-11e6-8bf2-552bb34035d4.png)

**Comment by davidoesch** [comment]
With vector tiles : again another story. Your summary is correct. But if the solution might be a Hydra: we solve one issue but generate others: explaining to customers that we have two different highlights is difficult, defining the snapping tolerance as well, the time does not correspond with the actual geometry downloaded as kml which will end up in further explanation effort. 
Nevertheless: can you give me a cost estimate in hours for dev of your proposed solution in the summary? I'll then again present this to our exec members and again try to get see what is needed to free up the geometry usage of hiking trails.

**Comment by davidoesch** [comment]
@gjn Test with up to 2000 points?

**Comment by davidoesch** [comment]
Other option: of profile is too long (eg 50km etc) and our sampling will result in high errors: we don't show hiking time ....

**Comment by davidoesch** [comment]
Ping @gjn
