### ISSUE TITLE
Fix grid Layer annotation org.epsg.grid_2056 org.epsg.grid_21781 org.epsg.grid_4326

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#3493]
For org.epsg.grid_2056 org.epsg.grid_21781 org.epsg.grid_4326 it is sometime not clear, which line the  annotation describes

Result: eg for 500m grid
![image](https://cloud.githubusercontent.com/assets/4577727/18625220/542bf9d2-7e4d-11e6-8b40-8a943c71bedb.png)

Expected result:
It is clear for which grid whcih annotation is used
![image](https://cloud.githubusercontent.com/assets/4577727/18625231/70863782-7e4d-11e6-84a2-8980abde99b1.png)

Task:
A) Check all the zoomlevels, they shall to fit this spec:

![image](https://cloud.githubusercontent.com/assets/4577727/19508734/16902a3a-95db-11e6-9fb6-8e70046679ec.png)

B) PDF make sure that for A4 portait and landscape at least 2 vertical and 2 horizontal lines stay visible
Action:
move the labels for all zoomlevels to the corresponding line in the WMS layer

AcCustomer feedback ID : 2016091520482807

When Done: inform Customer feedback ID : 2016091520482807

**Comment by loicgasser** [comment]
@ltclm Any plan to address this?

**Comment by ltclm** [comment]
not yet. will have to investigate what has to be done...

**Comment by gjn** [comment]
ping @AFoletti @ltclm

**Comment by AFoletti** [comment]
@alcapat resumed work on this issue. He is making the whole visibility better, checking the 03/95 compatibility (in order to see both annotations when you activate both grids) and fixing the grid size in order to comply with the specs

**Comment by AFoletti** [comment]
sorry, wrong button

**Comment by AFoletti** [comment]
Print scale | distance for LV
------------|--------------
1:2'500'00|100km
1:1'500'000|100km
1:1'000'000|75km
1:500'000|40km
1:300'000|20km
1:200'000|15km
1:100'000|5km
1:50'000|4km
1:25'000|2km
1:20'000|1km
1:10'000|500m
1:5'000|250m
1:2'500|150m
1:1'000|50m
1:500|25m

Hello @alcapat 
Here the new grid definition per print level for both LV03 and LV95. WSG84 stays the same as above.
About labeling and optimizing please:
- optimize layout for LV95 (for for vertical and horizontal lines)
- set LV03 with the same offset as LV95, so that when both layers are activated, LV95 is still correctly visualized and LV03 is hidden behind

**Comment by AFoletti** [comment]
I tested on screen and on paper each zoomlevel using [this link](https://s.geo.admin.ch/780bbb8e41)
I have a single change request: please make the line distance 25km instead of 40km for the 1:300'000 (i cahnged the table in the previous post too).

Once is done, this is in my opinion good to go to prod

**Comment by AFoletti** [comment]
changes are online. Thanks for your work!
