### ISSUE TITLE
[catalog/layerselector] solution for shop layers with long names

### ISSUE THREAD

**Issue by mariokeusen** [geoadmin/mf-geoadmin3#3568]
This is a ticket resulting from the latest shop decisions:

UC: open https://s.geo.admin.ch/6f267300bf, watch the loaded layer in catalog and in layer selector
Result: after the latest decisions in the shop-layer project / layer concept there are resulting a bunch of layers with more than 35 char in the alternative title. In this example, the name of the layer in the selector and catalog is truncated
Expected: full layer name is readable

**Comment by gjn** [comment]
The behaviour is as defined. If it's too long, we truncate it. So if we want to change it, we need to know how:

1) Do we make it 2 lines?
2) Do we increase width of the layer manager? If so, to what size? How on mobile?
3) Do we display tooltip with whole name on hover?

ping @davidoesch

**Comment by mariokeusen** [comment]
see email with few proposals...

**Comment by davidoesch** [comment]
works as defnied
a nice to have is: display whole name when on hover

reason why trunctation makes sense: and not full name
- mobile: hard to implement ( text size, width box)
- length: there  *has* to be a limit, even for +35 char ..is it 50? 100? with truncatatiosn we have done pareto: it works for every case
- in layer tree: with all the intends, names  have to be shorter than 25 char.. since in layertree a two line  approach makes it even complicater
- user centered design: user finds data mostly via toposhop  or search : so he won't even need the tree on the left
- aligned with our policy: if longer than 35 char - we cut it


this is why I gracefully close the ticket

**Comment by cedricmoullet** [comment]
I propose to do exactly like in the catalog: onhover to show the name.

**Comment by oterral** [comment]
Pr merged
