### ISSUE TITLE
Print PDF: marker not shown

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#3794]
ALL OS / ALL browsers

since last deploy
map.geoa.dmin.ch
Enter "raron"
Click print
result: pdf does not contain marker

expected result:
PDf has a marker

Observation:
IF marker is removed before printing by clicking in search. on chrome PDF generation is faster.

**Comment by oterral** [comment]
The print server can't access this image via cloudfront.

Without cloud front it works.

**Comment by davidoesch** [comment]
I move this to showstopeper since we have a lot of complaints

**Comment by gjn** [comment]
What is the url that fails from the print server?

**Comment by gjn** [comment]
https://map.geo.admin.ch/master/688362f/1704261351/1704261351/img/marker.png

@procrastinatio Any idea why print would have problems with this?

**Comment by gjn** [comment]
I think it's missing  `Access-Control-Allow-Origin: *` header. I try to adapt in cloudfront settings.

**Comment by gjn** [comment]
What I did didn't help.

**Comment by gjn** [comment]
A quick fix would be to use the technical url for the marker URL when passing it to the print. We could do this for next wee.

I tried to find out why print can't load resources from cloudfront, but can't find the logs - or didn't find anything in the logs on the production machines.

**Comment by procrastinatio** [comment]
Please use https://github.com/geoadmin/service-print/issues/29, this is not a mf-geoadmin3 issue.

**Comment by procrastinatio** [comment]
@gjn, it is not a web request, `Access-Control-Allow-Origin: *` should not change anything.

**Comment by procrastinatio** [comment]
@gjn the logs are pretty lame, with only a:
`[Wed May 03 17:03:13 2017] [error] (70007)The timeout specified has expired: proxy: dialog to (null) (*) failed`

**Comment by gjn** [comment]
Might be related to http2. I test.

**Comment by gjn** [comment]
It seems like the Jakarta Commons-HttpClient/3.1 client used by the print can't get anything from cloudfront. It's old client (5 years old) and probably doesn't understand some modern http protocol negotions.

Shortterm solution: use technical address for this resource
Midterm solution: move those resource out of CloudFront
Longterm solution: update print

**Comment by gjn** [comment]
https://github.com/geoadmin/service-print/issues/29

**Comment by gjn** [comment]
btw: this issue can be seen in [kibana](https://kibana.bgdi.ch/app/kibana#/visualize/edit/62bb5380-31a8-11e7-be46-97fd369119ce?_g=(refreshInterval%3A(display%3AOff%2Cpause%3A!f%2Cvalue%3A0)%2Ctime%3A(from%3Anow-30d%2Cmode%3Aquick%2Cto%3Anow))) as increased error rate since april 25th - the day we switched map.geo to cloudfront:

Around 150 prints per day fail because of it.

We have [3000-6000 prints](https://kibana.bgdi.ch/app/kibana#/discover/aa0cd050-31a9-11e7-be46-97fd369119ce?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:now-60d,mode:quick,to:now))&_a=(columns:!(_source),filters:!(('$$hashKey':'object:17719','$state':(store:appState),meta:(alias:!n,disabled:!f,index:'normalized_logs-*',key:requestHost,negate:!f,value:print.geo.admin.ch),query:(match:(requestHost:(query:print.geo.admin.ch,type:phrase)))),('$$hashKey':'object:17720','$state':(store:appState),meta:(alias:!n,disabled:!f,index:'normalized_logs-*',key:verb,negate:!f,value:POST),query:(match:(verb:(query:POST,type:phrase))))),index:'normalized_logs-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:create.json)),sort:!(timegenerated,desc))) per day

**Comment by gjn** [comment]
Fixed in production with ugly hack.
