### ISSUE TITLE
Map.revision.ch:  permalink does not work anymore

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#4388]
http://map.revision.admin.ch/?X=189216&Y=820916&zoom=13&layers=ch.bfe.solarenergie-eignung-daecher&bgLayer=ch.swisstopo.swissimage

result
ch.bfe.solarenergie-eignung-daecher not shown

expected result 

ch.bfe.solarenergie-eignung-daecher  shown

**Comment by gjn** [comment]
This is the re-direction from map.revision.admin.ch which is this:

https://map.geo.admin.ch/?topic=swisstopo&widgets=feedback&layers=ch.swisstopo.meldungen-karten_geodaten

Because it contains the layers parameter (to add the revision layer), it overwrites whatever other layers there are. All other parameters not in the re-direction are kept.

I assume the re-direction was changed some time to add the layers parameter, resulting in this problem.

A dynamic re-direct (one which accumulates the layers parameters) would be quite complicated. Maybe we can work with the referer and 'hack' something in the application (if referer is map.revision, then add meldungen layer), but the re-direct would need to be adapted.

**Comment by davidoesch** [comment]
Martin

Use this url parameters

http://map.geo.admin.ch/?X=189216&Y=820916&zoom=13&layers=ch.bfe.solarenergie-eignung-daecher&bgLayer=ch.swisstopo.swissimage&widgets=feedback
