### ISSUE TITLE
CORS-Header-Warnung (ev. unproblematisch)

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#4501]
related maybe to #4500 and https://groups.google.com/forum/#!topic/geoadmin-api/DutPuA1qVoE

> 
> Bei wandern.ch sowie wandern-stage.ch bekommen wir eine Warnung in der Javascript-Konsole:
>  
> (Cross-Origin) Anfrage blockiert: Die Gleiche-Quelle-Regel verbietet das Lesen der externen Ressource auf https://www.wandern-stage.ch/tmp/kml/7d69564b48218531962088c3c3989198.kml. (Grund: CORS-Kopfzeile 'Access-Control-Allow-Origin' fehlt)
>  
> URLs:
> - https://www.wandern-stage.ch/de/wandern/unsere-wandervorschlaege/alle-wandervorschlaege
> - https://www.wandern.ch/de/wandern/unsere-wandervorschlaege/alle-wandervorschlaege
>  
> Diese Warnung erscheint immer, auch wenn das KML gerendert wird. Wir wissen nicht, ob das früher schon so war, es ist uns erst heute aufgefallen
> 
>

**Comment by procrastinatio** [comment]
No, to decide if we have to use the proxy or not, we check HTTPS and if CORS header are present with a HEAD request (see https://github.com/geoadmin/mf-geoadmin3/blob/9f01ccb14e7ade35069bdeeaaabc33ba85a88631/src/components/UrlUtilsService.js#L56). As the response doesn't have the CORS header, it makes the console warning and we use the proxy.

Solution, set your staging and production server with the CORS header

HTTPS :-) but no CORS :-(

```
curl -I https://www.wandern-stage.ch/tmp/kml/7d69564b48218531962088c3c3989198.kml
HTTP/1.1 200 OK
Date: Thu, 20 Sep 2018 21:26:52 GMT
Server: Apache
Upgrade: h2
Connection: Upgrade
Last-Modified: Thu, 20 Sep 2018 14:40:22 GMT
ETag: "145d98-5764e80ba083a"
Accept-Ranges: bytes
Content-Length: 1334680
NZSpeedy: OFF
X-XSS-Protection: 0
```

**Comment by silvercode-ch** [comment]
Thanks a lot, we set the CORS header for map.geo.admin.ch on the stage server and the CORS messages are gone.
We will do the same for production server next week.

**Comment by silvercode-ch** [comment]
Now we find a strange behaviour.

Oh this page: 
https://www.wandern-stage.ch/zuercher-wanderwege.ch/de/ewalc
there are no CORS warings.

but here:
https://www.wandern-stage.ch/de/wandern/unsere-wandervorschlaege/alle-wandervorschlaege
appears now the message: CORS request did not succeed

On both URL works the same application.

About the message I found the following post on mozilla's dev site:
https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors/CORSDidNotSucceed
"The HTTP request which makes use of CORS failed because the HTTP connection failed at either the network or protocol level. The error is not directly related to CORS, but is a fundamental network error of some kind."

CURL mean:
`curl -I https://www.wandern-stage.ch/tmp/kml/da924d63807285c856be22ae07731c9f.kml
HTTP/2 200 
date: Fri, 21 Sep 2018 16:05:01 GMT
server: Apache
last-modified: Fri, 21 Sep 2018 16:00:03 GMT
etag: "f95-57663bb88b807"
accept-ranges: bytes
content-length: 3989
nzspeedy: OFF
x-xss-protection: 0
**access-control-allow-origin: https://map.geo.admin.ch**
nzx: OK
content-type: application/vnd.google-earth.kml+xml`

Do you have any tips?

**Comment by procrastinatio** [comment]
Hello,

My understanding is the following. To decide wether we must use the proxy or not, goe.admin.ch is doing first a HEAD request:

```
curl 'https://www.wandern-stage.ch/tmp/kml/fb74ac11d7e45e1fbffd68695ad13318.kml' -I  -H 'Referer: https://map.geo.admin.ch/embed.html?zoom=0&topic=ech&lang=de&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=KML%7C%7Chttps:%2F%2Fwww.wandern-stage.ch%2Ftmp%2Fkml%2Ffb74ac11d7e45e1fbffd68695ad13318.kml&layers_visibility=true' -H 'Origin: https://map.geo.admin.ch'   ```

As the response lack all required CORS header, an error is issued in the console and the GET request is going through the proxy, which succeed.

```
Access-Control-Allow-Origin:
Access-Control-Allow-Methods: 
Access-Control-Allow-Headers: 
```

The only difference is **FF** show the error, and **chrome** doesn't

So if you configure the right headers for `HEAD`, the subsequent `GET`request won't go through the proxy.

**Comment by davidoesch** [comment]
ping @silvercode-ch solved?
