### ISSUE TITLE
[MVT] Borders over text

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#4721]
open https://s.geo.admin.ch/7fdf489857

on win10 chrome

![image](https://user-images.githubusercontent.com/4577727/52178444-e62d8580-27ce-11e9-9f45-9ed2c416cf88.png)

expected: country border is behind text

**Comment by swissgis3084** [comment]
same issue as #4739 ?

**Comment by swissgis3084** [comment]
seems that order of layers is different than specified in the style?

**Comment by pakb** [comment]
that's a separate issue. It's caused by the fact that we make two layer groups in OpenLayers for both sources (OSM and Swisstopo), and those sources are managed separately for declutering and ordering.

As we can't juridically merge the two sources in the style, the only way to solve this would be to programmatically merge the two sources with a custom OL loader (as proposed on this PR https://github.com/geoadmin/mf-geoadmin3/pull/4523). I'll give it a try when bigger issues are fixed.

**Comment by pakb** [comment]
Now that OSM cut is good with labels (no more labels over Switzerland), we should have OSM labels over our data (but beneath our labels) in the style JSON.
Is that OK with you @swissgis3084 ?

**Comment by davidoesch** [comment]
We will take this into the project steering group

**Comment by swissgis3084** [comment]
where can I see it? currently I can see this: (https://test.map.geo.admin.ch)
![image](https://user-images.githubusercontent.com/42927494/53956676-90554180-40dc-11e9-9c46-3142169a6417.png)
Not sure if these kind of Problems can ever be solved, if OpenLayers creates seperate layer groups for OSM and swisstopo data

**Comment by pakb** [comment]
this happens because layers are ordered this way in our style :

- OSM data
- OSM Labels
- Swisstopo data
- Swisstopo Labels
- OSM Country labels

If we would placed OSM labels after our data, foreign labels would be on top of lakes and such features.
