### ISSUE TITLE
Wmts Stadt-Zurich.ch not displaying

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#5094]
Try to load öffentliche Parkplätze via Import 

https://www.ogd.stadt-zuerich.ch/mapproxy/wmts/1.0.0/WMTSCapabilities.xml

Result
Not working

https://s.geo.admin.ch/863df01640

**Comment by pakb** [comment]
![image](https://user-images.githubusercontent.com/11540521/70974436-0a711880-20a8-11ea-9491-e99afe082ac5.png)
Is that what it should output? If so, maybe verify out of Bund network (I'm on my 4G and this is what I get)

**Comment by p1d1d1** [comment]
In Bund net working in FF, not working in EDGE

**Comment by pakb** [comment]
Well, then it's out of the scope of what I can manage. I'm closing this.

**Comment by davidoesch** [comment]
Nope : it does not work on safari Chrome on ios13

**Comment by pakb** [comment]
![image](https://user-images.githubusercontent.com/11540521/70994241-0f48c300-20ce-11ea-9d3e-4c8a161271a4.png)
[that's why](https://www.ogd.stadt-zuerich.ch/cookie-check/CookieCheckError.html?trg=RT_BToGP_KHK9W_MR0OfANbg94LUoBgmpDSm1BQhk7mUp32PUZX8y_6tKxabrL-YeU6LowsWF_dBpnJ6c9NzcyYaHqoXGmgFsJ8RLKxNht2EnbWr4naRE81-u8CtUUEmV8JjFv10CSyCgmCRBSqgou3zzLCX2-Sl).

**Comment by pakb** [comment]
And I'd like to say (it's only my opinion though) that this kind of problem shouldn't come up as a bug on Github but be first processed by our support team. This is level 1 support not something an engineer needs to be involved in order to find the problem.

**Comment by pakb** [comment]
TD;DR; we don't do cookies on geoadmin, either they allow access to their data without cookie acceptance, or we can't show their data

**Comment by procrastinatio** [comment]
The same doc on https://www.procrastinatio.org/WMTS/WMTSCapabilities.ZH.xml works well.

**Comment by pakb** [comment]
So CORS related?! And I haven't seen your line : "We're in 2019 and people don't know how to do CORS"?! 😄

**Comment by procrastinatio** [comment]
@pakb Partly.
The thing is even in 2019, many external servers are still correctly configured for `CORS`. We make a `HEAD` request, and decide if we have to use or not our proxy to get the resource. 

In my view the two options are
* All external resources go through the proxy, **or, even better,** 
* We ditch the proxy, and _tant pis_. Some people have a valid reason not to use CORS.

**Comment by davidoesch** [comment]
CORS on Desktop no issue but on mobile... to complex for me

**Comment by boecklic** [comment]
@boecklic commented: ![image](https://user-images.githubusercontent.com/11540521/70974436-0a711880-20a8-11ea-9491-e99afe082ac5.png)
Is that what it should output? If so, maybe verify out of Bund network (I'm on my 4G and this is what I get)

**Comment by boecklic** [comment]
@boecklic commented: In Bund net working in FF, not working in EDGE

**Comment by boecklic** [comment]
@boecklic commented: Well, then it's out of the scope of what I can manage. I'm closing this.

**Comment by boecklic** [comment]
@boecklic commented: Nope : it does not work on safari Chrome on ios13

**Comment by boecklic** [comment]
@boecklic commented: ![image](https://user-images.githubusercontent.com/11540521/70994241-0f48c300-20ce-11ea-9d3e-4c8a161271a4.png)
[that's why](https://www.ogd.stadt-zuerich.ch/cookie-check/CookieCheckError.html?trg=RT_BToGP_KHK9W_MR0OfANbg94LUoBgmpDSm1BQhk7mUp32PUZX8y_6tKxabrL-YeU6LowsWF_dBpnJ6c9NzcyYaHqoXGmgFsJ8RLKxNht2EnbWr4naRE81-u8CtUUEmV8JjFv10CSyCgmCRBSqgou3zzLCX2-Sl).

**Comment by boecklic** [comment]
@boecklic commented: TL;DR; we don't do cookies on geoadmin, either they allow access to their data without cookie acceptance, or we can't show their data

But there's something fishy, we are redirected to this page CookieCheck... But if I access image directly from iOs Safari, I don't get any CookieCheck weird stuff

**Comment by boecklic** [comment]
@boecklic commented: The same doc on https://www.procrastinatio.org/WMTS/WMTSCapabilities.ZH.xml works well.

**Comment by boecklic** [comment]
@boecklic commented: So CORS related?! And I haven't seen your line : "We're in 2019 and people don't know how to do CORS"?! 😄

**Comment by boecklic** [comment]
@boecklic commented: @pakb Partly.
The thing is even in 2019, many external servers are still correctly configured for `CORS`. We make a `HEAD` request, and decide if we have to use or not our proxy to get the resource. 

In my view the two options are
* All external resources go through the proxy, **or, even better,** 
* We ditch the proxy, and _tant pis_. Some people have a valid reason not to use CORS.

**Comment by boecklic** [comment]
@boecklic commented: CORS on Desktop no issue but on mobile... to complex for me

**Comment by gemetris** [comment]
Hello. I have the same (or similar) issue with a "private" WMS service published by ArcGIS Enterprise/Portal.
I'm getting a CORS error with Chrome or Edge.
Problem seems to be related to the proxy used by GeoAdmin. 
In some other geoportals I tested, it works.

It says me "Access to XMLHttpRequest at 'https://service-proxy.prod.bgdi.ch/https...' from origin 'https://map.geo.admin.ch' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource."

But if I add an explicite 'Access-Control-Allow-Origin' rule at my side (should not be needed I think), I'm getting "Access to XMLHttpRequest at '...' from origin 'https://map.geo.admin.ch' has been blocked by CORS policy: The 'Access-Control-Allow-Origin' header contains multiple values 'https://map.geo.admin.ch, *', but only one is allowed.

I'm not sure where the problem is (perhaps ArcGIS adds automatically request URL to response (map.geo.admin.ch)), but anyway this headers seem be make problem with your proxy https://service-proxy.prod.bgdi.ch (not detected or then multiple).

Is this ticket still at work?
Best regards and thanks

Note: the WMS service I'm trying to use is not really public and at this time only for tests purposes at my side, it's why I dont write the URL here. But if needed I can give you the URL somehow!

**Comment by davidoesch** [comment]
works
