### ISSUE TITLE
location service  mobile on Android 8.0.0; SM-G935F  not working

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#5199]
The location service isn't working. The error message ("The acquisition of the position failed ...") is wrong as the site doesn't ask for the right permission. It only asks for sound permission and not location.

I'm using Chrome on newest Android but tried with the build in browser and had the same issue..

Permalink: https://map.geo.admin.ch/mobile.html?topic=ech&lang=en&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=ch.swisstopo.swisstlm3d-wanderwege&layers_opacity=0.8&E=2662990.00&N=1203755.00&zoom=4.

User-Agent: Mozilla/5.0 (Linux; Android 8.0.0; SM-G935F) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Mobile Safari/537.36

Application Version: 2005271117

Customer feedback ID : 2020080214203212

**Comment by kevindullemond** [comment]
End user here, the issue lies with https://www.nw-wanderwege.ch/de/where-am-i .

If I use your permalink it works for me (in fact I came here to report that the workaround for this issue is going to https://map.geo.admin.ch/ directly). So it seems like a cross site permission problem (nw-wanderwege.ch embeds map.geo.admin.ch). 

Good luck and thanks for the great resource.

**Comment by davidoesch** [comment]
So you must contact the wanderwege site admin
I close this.
Have a good weekend
