### ISSUE TITLE
Layer Attributes Query for Schweizerischer Nationalpark not working

### ISSUE THREAD

**Issue by ltruba** [geoadmin/mf-geoadmin3#5294]
I just found this bug.  The query of the layer attributes for "Swiss National Park" does not work, although the query of the legend works.

**working example**
https://api3.geo.admin.ch/rest/services/bafu/MapServer/ch.bafu.schutzgebiete-schweizerischer_nationalpark/legend

**non working example**
https://api3.geo.admin.ch/rest/services/bafu/MapServer/ch.bafu.schutzgebiete-schweizerischer_nationalpark
Response:
{"detail":"No Vector Table was found for ch.bafu.schutzgebiete-schweizerischer_nationalpark","status":"error","code":400}

**Comment by davidoesch** [comment]
Hi we will address this in our internal ticket system https://jira.swisstopo.ch/browse/BGDIDIC-2539 ... we try to report the fix here as well

**Comment by rebert** [comment]
Thanks for your feedback @ltruba 

I looked at this the layer `ch.bafu.schutzgebiete-schweizerischer_nationalpark` and can confirm, that query https://api3.geo.admin.ch/rest/services/bafu/MapServer/ch.bafu.schutzgebiete-schweizerischer_nationalpark returns a HTTP 400 - Bad Request. This happens, because this layer has neither a tooltip nor a vector model configured (by purpose - as an option chosen by the data owner). The same behavior can be obtained on all raster layers. Here is an example: https://sys-api3.dev.bgdi.ch/rest/services/bafu/MapServer/ch.bafu.neophyten-japanisches_geissblatt .

BR

I'm going to inform the client about that.

BR
Tobias.
